/* ============================================================
   RUTA PAA — Banco de preguntas (ORIGINALES, estilo PAA)
   No son las preguntas del folleto oficial: son nuevas, creadas con la
   misma estructura y temario para que tengás material fresco.

   Esquema de cada pregunta:
   { id, domain:'verbal'|'math', topic:'<id de topics.js>', dif:1|2|3,
     stem:'enunciado', q:'la pregunta', opts:[a,b,c,d], ans:índice 0-3,
     exp:'explicación' }

   Para agregar más: copiá un objeto, cambiá el id y sumalo al array.
   ============================================================ */
window.PAA_QUESTIONS = [
  /* ===================== VERBAL ===================== */

  /* -- Finalidad -- */
  { id:"v_fin_1", domain:"verbal", topic:"finalidad", dif:3,
    stem:"Desde hace una década, varias municipalidades instalaron reductores de velocidad, semáforos peatonales y pasos elevados cerca de escuelas y hospitales. Estas obras encarecen el mantenimiento y a veces molestan a los conductores, pero las autoridades insisten en conservarlas.",
    q:"¿Cuál es la finalidad principal de las autoridades con estas obras?",
    opts:["Recaudar más dinero mediante multas","Proteger la vida de los peatones en zonas sensibles","Incomodar a propósito a los conductores","Reducir el gasto en mantenimiento vial"],
    ans:1, exp:"El texto presenta los costos y molestias como obstáculos que las autoridades aceptan; el fin que justifica conservar las obras es proteger a los peatones cerca de escuelas y hospitales." },
  { id:"v_fin_2", domain:"verbal", topic:"finalidad", dif:3, stem:"Marta destina una parte fija de su salario a un fondo cada mes. Aunque eso la obliga a renunciar a algunos gustos hoy, ella explica que lo hace pensando en comprar casa propia antes de los cuarenta.", q:"¿Cuál es la finalidad del ahorro de Marta?", opts:["Privarse de gustos en el presente","Comprar casa propia en el futuro","Demostrar disciplina a los demás","Aumentar su salario mensual"], ans:1, exp:"La finalidad es el para qué: comprar casa propia. Renunciar a gustos es el medio, no el fin." },
  { id:"v_fin_3", domain:"verbal", topic:"finalidad", dif:2,
    stem:"El profesor repite varias veces los conceptos más difíciles durante la clase para que sus estudiantes los comprendan mejor.",
    q:"¿Cuál es la finalidad de repetir los conceptos?",
    opts:["Alargar la clase","Facilitar la comprensión","Demostrar su conocimiento","Evaluar a los estudiantes"],
    ans:1, exp:"Se repite 'para que comprendan mejor'. La finalidad es facilitar la comprensión." },

  /* -- Comportamiento -- */
  { id:"v_com_1", domain:"verbal", topic:"comportamiento", dif:2, stem:"Cada vez que recibe una crítica sobre su trabajo, Luis, en lugar de leerla completa, responde al instante defendiéndose y enumerando excusas, sin detenerse a pensar si el comentario tenía algo de razón.", q:"¿Cómo se comporta Luis ante las críticas?", opts:["Las analiza con calma","Reacciona a la defensiva sin escuchar","Las agradece y mejora","Las ignora por completo"], ans:1, exp:"Responder de inmediato con excusas y sin considerar la crítica es reaccionar a la defensiva." },
  { id:"v_com_2", domain:"verbal", topic:"comportamiento", dif:3, stem:"Ante el menor ruido extraño, el conejo no corre ni intenta atacar: se queda completamente inmóvil, pegado al suelo, confiando en que su quietud lo vuelva difícil de notar para el depredador.", q:"¿Cómo se comporta el conejo ante una posible amenaza?", opts:["Huye a toda velocidad","Se queda inmóvil para pasar desapercibido","Ataca al depredador","Hace ruido para asustarlo"], ans:1, exp:"El texto dice que no corre ni ataca: se queda inmóvil para no ser notado." },
  { id:"v_com_3", domain:"verbal", topic:"comportamiento", dif:2,
    stem:"Algunas personas, cuando reciben una crítica, en lugar de escuchar responden de inmediato a la defensiva.",
    q:"¿Cómo se comportan estas personas ante una crítica?",
    opts:["Reflexionan con calma","Reaccionan a la defensiva","La ignoran por completo","Agradecen el comentario"],
    ans:1, exp:"La conducta descrita es reaccionar a la defensiva." },

  /* -- Causa y consecuencia -- */
  { id:"v_cau_1", domain:"verbal", topic:"causa_consecuencia", dif:3, stem:"La tala excesiva en la parte alta dejó las laderas sin árboles. Sin raíces que retuvieran la tierra, las primeras lluvias fuertes arrastraron el suelo y enturbiaron el río del que bebe la comunidad.", q:"Según el texto, ¿cuál es una consecuencia de la tala?", opts:["El aumento de árboles en la zona","La contaminación del río por el arrastre de tierra","La mejora de la calidad del agua","La llegada de más lluvias"], ans:1, exp:"Sin raíces, la lluvia arrastró el suelo y enturbió el río: esa es la consecuencia." },
  { id:"v_cau_2", domain:"verbal", topic:"causa_consecuencia", dif:2, stem:"Diversos estudios señalan que dormir mal de manera constante no solo produce cansancio: con el tiempo afecta la memoria, debilita las defensas del cuerpo y aumenta la irritabilidad.", q:"Según el texto, ¿qué puede causar dormir mal de forma constante?", opts:["Mejor memoria","Problemas de memoria, defensas y ánimo","Más energía durante el día","Mayor concentración"], ans:1, exp:"El texto enumera los efectos de dormir mal: afecta memoria, defensas e irritabilidad." },
  { id:"v_cau_3", domain:"verbal", topic:"causa_consecuencia", dif:2, stem:"El equipo no era el más talentoso de la liga, pero entrenó con disciplina todos los días, corrigió sus errores tras cada partido y llegó a la final con la mejor condición física. Al final, se llevó el campeonato.", q:"Según el texto, ¿qué explica mejor el triunfo del equipo?", opts:["El talento natural de sus jugadores","El trabajo constante y la corrección de errores","La suerte en los partidos decisivos","La debilidad de los rivales"], ans:1, exp:"El texto aclara que NO eran los más talentosos, así que A se descarta. No menciona suerte (C) ni rivales débiles (D). La causa que sí repite es el entreno disciplinado y corregir errores: por eso B." },
  { id:"v_cau_4", domain:"verbal", topic:"causa_consecuencia", dif:2,
    stem:"El uso prolongado de pantallas antes de dormir dificulta conciliar el sueño.",
    q:"¿Qué relación se establece en el texto?",
    opts:["El sueño causa el uso de pantallas","El uso de pantallas dificulta el sueño","Las pantallas mejoran el sueño","No hay relación entre ambos"],
    ans:1, exp:"La causa es el uso de pantallas; la consecuencia, la dificultad para dormir." },

  /* -- Simple y complejo -- */
  { id:"v_sim_1", domain:"verbal", topic:"simple_complejo", dif:2,
    stem:"Un reloj de arena solo mide el tiempo con la caída de granos; en cambio, un reloj digital integra sensores, batería y múltiples funciones.",
    q:"Según el texto, ¿en qué se diferencian ambos relojes?",
    opts:["Uno es antiguo y el otro nuevo","Uno es simple y el otro complejo","Uno es barato y el otro caro","Uno es pequeño y el otro grande"],
    ans:1, exp:"El contraste central es entre un mecanismo de un solo elemento (simple) y otro de muchos componentes (complejo)." },
  { id:"v_sim_2", domain:"verbal", topic:"simple_complejo", dif:3, stem:"Encender un fósforo requiere un solo gesto. En cambio, mantener encendida una central termoeléctrica implica coordinar combustible, turbinas, sistemas de enfriamiento, controles de seguridad y decenas de operarios trabajando las 24 horas.", q:"¿Qué diferencia esencial plantea el texto entre ambas acciones?", opts:["Una es más antigua que la otra","Una es simple y la otra, compleja por sus muchas partes","Una es más cara que la otra","Una es más peligrosa que la otra"], ans:1, exp:"El contraste es entre un acto de un solo paso (simple) y otro con muchísimas partes coordinadas (complejo)." },
  { id:"v_sim_3", domain:"verbal", topic:"simple_complejo", dif:2,
    stem:"Una choza se levanta con unos pocos materiales; un rascacielos necesita ingeniería, miles de materiales y años de trabajo.",
    q:"¿Cómo se presenta el rascacielos frente a la choza?",
    opts:["Como algo simple","Como algo complejo","Como algo inútil","Como algo económico"],
    ans:1, exp:"El rascacielos se describe por su gran cantidad de partes y procesos: como algo complejo." },

  /* -- Conceptualización -- */
  { id:"v_con_1", domain:"verbal", topic:"conceptualizacion", dif:2,
    stem:"Quien comparte lo que tiene con los demás, sin esperar nada a cambio, practica una de las virtudes más valoradas.",
    q:"Según el texto, ¿cuál palabra describe esa virtud?",
    opts:["Generosidad","Justicia","Paciencia","Humildad"],
    ans:0, exp:"Compartir sin esperar nada a cambio se resume en el concepto de generosidad." },
  { id:"v_con_2", domain:"verbal", topic:"conceptualizacion", dif:2,
    stem:"El estudiante revisó cada dato, comprobó las fuentes y no aceptó ninguna afirmación sin evidencia.",
    q:"¿Cómo puede describirse, en una palabra, su actitud?",
    opts:["Rigurosa","Indiferente","Apresurada","Confiada"],
    ans:0, exp:"Verificar todo y exigir evidencia es propio de una actitud rigurosa." },
  { id:"v_con_3", domain:"verbal", topic:"conceptualizacion", dif:2, stem:"El corredor tropezó y cayó tres veces durante la carrera. Cada vez se levantó, recuperó el ritmo y siguió, hasta cruzar la meta en último lugar pero sin rendirse.", q:"¿Qué cualidad refleja mejor su actitud?", opts:["Velocidad","Perseverancia","Ambición","Talento"], ans:1, exp:"Llegó último, así que no destaca por velocidad (A) ni talento (D), y no se habla de querer más (ambición, C). Lo que lo define es insistir tras cada caída: perseverancia (B)." },
  { id:"v_con_4", domain:"verbal", topic:"conceptualizacion", dif:2, stem:"Le confiaron un secreto delicado. Aunque varias personas trataron de sonsacárselo e incluso sus amigos le preguntaron con insistencia, no soltó ni una palabra.", q:"¿Qué palabra describe mejor su actitud?", opts:["Discreción","Timidez","Indiferencia","Astucia"], ans:0, exp:"Guardar lo confiado pese a la presión es discreción (A). No es timidez (B: no calla por miedo), ni indiferencia (C: sí le importa), ni astucia (D: no engaña a nadie)." },

  /* -- Orden y desorden -- */
  { id:"v_ord_1", domain:"verbal", topic:"orden_desorden", dif:2,
    stem:"Antes de la reunión, los documentos estaban amontonados sin clasificación; después, quedaron archivados por fecha y tema.",
    q:"Según el texto, ¿qué cambio experimentaron los documentos?",
    opts:["Del orden al desorden","Del desorden al orden","De lo nuevo a lo viejo","De lo público a lo privado"],
    ans:1, exp:"Pasaron de estar amontonados (desorden) a estar archivados por criterio (orden)." },
  { id:"v_ord_2", domain:"verbal", topic:"orden_desorden", dif:2, stem:"Antes, las herramientas del taller se amontonaban en cualquier rincón y nadie hallaba nada a tiempo. Tras una jornada de organización, cada una quedó colgada en un panel y rotulada según su uso.", q:"¿Qué cambio experimentó el taller?", opts:["Del orden al desorden","Del desorden al orden","De lo nuevo a lo viejo","De lo barato a lo caro"], ans:1, exp:"Pasó de herramientas amontonadas (desorden) a cada una rotulada en su lugar (orden)." },
  { id:"v_ord_3", domain:"verbal", topic:"orden_desorden", dif:2, stem:"Después de la mudanza, las cajas quedaron apiladas sin etiquetas, los libros mezclados con la vajilla y la ropa repartida entre varias habitaciones, sin que nada estuviera en su sitio.", q:"¿Cómo se describe el estado de la casa tras la mudanza?", opts:["En perfecto orden","En completo desorden","Totalmente vacía","Recién pintada"], ans:1, exp:"Cajas sin etiqueta, cosas mezcladas y todo fuera de su sitio describen desorden." },

  /* -- Orden temporal -- */
  { id:"v_tmp_1", domain:"verbal", topic:"orden_temporal", dif:2,
    stem:"Primero se mezclan los ingredientes secos, luego se añade la leche y, por último, se hornea la masa.",
    q:"Según el texto, ¿qué se hace inmediatamente antes de hornear?",
    opts:["Mezclar los ingredientes secos","Añadir la leche","Servir el pastel","Encender el horno"],
    ans:1, exp:"La secuencia es secos → leche → hornear. Justo antes de hornear se añade la leche." },
  { id:"v_tmp_2", domain:"verbal", topic:"orden_temporal", dif:2, stem:"La receta indica: primero batir los huevos con el azúcar, luego incorporar la harina poco a poco, después verter la mezcla en el molde y, por último, hornear durante 40 minutos.", q:"Según la receta, ¿qué se hace inmediatamente antes de hornear?", opts:["Batir los huevos","Verter la mezcla en el molde","Incorporar la harina","Servir el postre"], ans:1, exp:"La secuencia es batir, harina, verter en el molde y hornear. Justo antes de hornear se vierte la mezcla." },
  { id:"v_tmp_3", domain:"verbal", topic:"orden_temporal", dif:2,
    stem:"La semilla germina, luego crece el tallo, después aparecen las hojas y finalmente brota la flor.",
    q:"Según el texto, ¿qué ocurre antes de que aparezcan las hojas?",
    opts:["Brota la flor","Crece el tallo","Cae la semilla","Se seca la planta"],
    ans:1, exp:"La secuencia es germinar → tallo → hojas → flor. Antes de las hojas crece el tallo." },

  /* -- Esencia -- */
  { id:"v_ese_1", domain:"verbal", topic:"esencia", dif:3,
    stem:"Un buen líder se caracteriza, generalmente, por escuchar a su equipo, tomar decisiones justas y dar el ejemplo.",
    q:"De acuerdo con la lógica del texto, ¿qué caracteriza generalmente a un buen maestro?",
    opts:["Escuchar a sus estudiantes, evaluar con justicia y enseñar con el ejemplo","Ordenar a sus estudiantes y exigir resultados","Dictar la materia y aplicar exámenes difíciles","Trabajar solo, sin ayuda de nadie"],
    ans:0, exp:"Por lógica paralela, las cualidades del líder (escuchar, justicia, ejemplo) se trasladan al maestro: escuchar, evaluar con justicia y enseñar con el ejemplo." },
  { id:"v_ese_2", domain:"verbal", topic:"esencia", dif:2,
    stem:"El agua, en su forma líquida, se caracteriza por no tener forma propia y adaptarse al recipiente que la contiene.",
    q:"Según el texto, ¿cuál es una característica esencial del agua líquida?",
    opts:["Tener color","Adaptarse al recipiente","Tener sabor","Mantener una forma fija"],
    ans:1, exp:"Lo propio del agua líquida, según el texto, es adaptarse al recipiente." },
  { id:"v_ese_3", domain:"verbal", topic:"esencia", dif:3,
    stem:"Lo propio de un desierto es la escasez de agua, las altas temperaturas durante el día y la poca vegetación.",
    q:"De acuerdo con la lógica del texto, ¿qué sería propio de una selva tropical?",
    opts:["Abundancia de agua, vegetación densa y mucha vida","Escasez de agua y poca vegetación","Frío extremo y nieve","Ausencia total de animales"],
    ans:0, exp:"Por contraste lógico con el desierto, lo propio de la selva es abundancia de agua, vegetación densa y abundante vida." },

  /* -- Perspectiva -- */
  { id:"v_per_1", domain:"verbal", topic:"perspectiva", dif:2,
    stem:"Observar un problema desde lejos es una cosa; vivirlo en carne propia es otra muy distinta.",
    q:"¿Cuál de las siguientes opciones presenta la idea del texto con otras palabras?",
    opts:["Observar y vivir un problema son experiencias diferentes","Observar un problema es más difícil que vivirlo","Vivir un problema no enseña nada","Observar y vivir son lo mismo"],
    ans:0, exp:"El texto contrasta dos perspectivas: observar y vivir son experiencias distintas." },
  { id:"v_per_2", domain:"verbal", topic:"perspectiva", dif:2,
    stem:"Para el agricultor, la lluvia es una bendición; para el viajero, un estorbo.",
    q:"Según el texto, ¿qué muestra esta diferencia de opiniones sobre la lluvia?",
    opts:["Que la lluvia es siempre dañina","Que un mismo hecho puede verse de distintas maneras","Que el agricultor está equivocado","Que la lluvia no afecta a nadie"],
    ans:1, exp:"Un mismo hecho (la lluvia) se valora distinto según la perspectiva de cada quien." },
  { id:"v_per_3", domain:"verbal", topic:"perspectiva", dif:2,
    stem:"Lo que para un niño es un juego sencillo, para un adulto puede parecer una pérdida de tiempo.",
    q:"¿Qué idea expresa el texto?",
    opts:["Los juegos son inútiles","Una misma actividad se valora distinto según quién la observe","Los niños no deben jugar","Los adultos no comprenden nada"],
    ans:1, exp:"La valoración depende del observador: niño y adulto ven la misma actividad de modo distinto." },

  /* -- Idea implícita -- */
  { id:"v_imp_1", domain:"verbal", topic:"idea_implicita", dif:2,
    stem:"Pedro siempre lleva paraguas cuando el cielo está nublado.",
    q:"¿Cuál es una idea implícita en el texto?",
    opts:["Pedro nunca se moja","Pedro toma precauciones ante la posibilidad de lluvia","A Pedro le gusta la lluvia","Pedro vende paraguas"],
    ans:1, exp:"Llevar paraguas con cielo nublado implica que se previene ante la posible lluvia." },
  { id:"v_imp_2", domain:"verbal", topic:"idea_implicita", dif:2,
    stem:"En esa comunidad, solo las personas que terminaron la universidad consiguen empleos bien pagados.",
    q:"¿Cuál es una idea implícita en el texto?",
    opts:["La educación influye en las oportunidades laborales","Nadie trabaja en esa comunidad","La universidad es gratuita","Todos ganan lo mismo"],
    ans:0, exp:"Si solo los graduados logran buenos empleos, se infiere que la educación influye en las oportunidades." },
  { id:"v_imp_3", domain:"verbal", topic:"idea_implicita", dif:2,
    stem:"Aunque el restaurante es caro, siempre está lleno de clientes.",
    q:"¿Qué idea está implícita en el texto?",
    opts:["La comida no gusta a nadie","El precio alto no ha alejado a los clientes","El restaurante va a cerrar","Los clientes no pagan"],
    ans:1, exp:"Que esté lleno a pesar de ser caro implica que el precio no ha alejado a la clientela." },
  { id:"v_imp_4", domain:"verbal", topic:"idea_implicita", dif:2,
    stem:"Cada vez que María estudia con anticipación, obtiene buenas notas.",
    q:"¿Cuál es una idea implícita?",
    opts:["Estudiar con tiempo favorece los buenos resultados","Las notas no dependen del estudio","María nunca estudia","Las buenas notas son por suerte"],
    ans:0, exp:"Se infiere una relación: estudiar con anticipación favorece las buenas notas." },
  { id:"v_imp_5", domain:"verbal", topic:"idea_implicita", dif:3,
    stem:"Cuando por fin se apagaron los motores de la fábrica y los últimos trabajadores se marcharon, en todo el valle solo quedó el rumor del viento moviendo las hojas.",
    q:"¿Qué se puede deducir con seguridad del texto?",
    opts:["La fábrica reabrirá al día siguiente","En ese momento reinaba el silencio en el lugar","Afuera había mucha gente conversando","Se acercaba una fuerte tormenta"],
    ans:1, exp:"Si lo único que se escucha es el viento entre las hojas, se deduce que el lugar quedó en silencio. Las demás opciones no se siguen del texto." },

  /* -- Idea principal / tema -- */
  { id:"v_pri_1", domain:"verbal", topic:"idea_principal", dif:2,
    stem:"Los volcanes pueden ser activos, inactivos o extintos; además, varían en tamaño y en el tipo de material que expulsan.",
    q:"¿Cuál es el tema principal del texto?",
    opts:["La clasificación de los volcanes","El peligro de los volcanes","La altura de los volcanes","La formación de los volcanes"],
    ans:0, exp:"El texto enumera tipos y variaciones: su tema es la clasificación de los volcanes." },
  { id:"v_pri_2", domain:"verbal", topic:"idea_principal", dif:2,
    stem:"El ejercicio regular fortalece el corazón y los músculos, mejora el ánimo al liberar endorfinas, favorece un sueño más profundo y ayuda a mantener un peso saludable; además, practicado en grupo, fortalece los vínculos sociales.",
    q:"¿Cuál es la idea principal del texto?",
    opts:["El ejercicio aporta múltiples beneficios para la salud y la vida","El ejercicio sirve únicamente para bajar de peso","Hacer ejercicio en grupo es obligatorio","Las endorfinas provocan cansancio"],
    ans:0, exp:"El texto enumera beneficios físicos, anímicos y sociales; la idea que los engloba es que el ejercicio aporta múltiples beneficios." },
  { id:"v_pri_3", domain:"verbal", topic:"idea_principal", dif:2,
    stem:"El café es una de las principales exportaciones de Costa Rica, genera empleo en zonas rurales y forma parte de su cultura.",
    q:"¿Cuál es el tema central del texto?",
    opts:["La importancia del café para Costa Rica","El sabor del café costarricense","El precio del café","La historia del café"],
    ans:0, exp:"Los tres rasgos (economía, empleo, cultura) apuntan al tema: la importancia del café para el país." },

  /* -- Paráfrasis -- */
  { id:"v_par_1", domain:"verbal", topic:"parafrasis", dif:2,
    stem:"El conocimiento es la única herramienta que nos protege de ser engañados.",
    q:"¿Cuál opción expresa la misma idea con otras palabras?",
    opts:["Saber nos defiende del engaño","El engaño es inevitable","El conocimiento engaña a las personas","Nadie puede aprender"],
    ans:0, exp:"'Saber nos defiende del engaño' conserva el sentido del texto. Las demás lo cambian o contradicen." },
  { id:"v_par_2", domain:"verbal", topic:"parafrasis", dif:2,
    stem:"No basta con desear el éxito; hay que trabajar para alcanzarlo.",
    q:"¿Cuál de las siguientes opciones reproduce la idea del texto?",
    opts:["El éxito llega solo con desearlo","El éxito requiere esfuerzo además de deseo","Desear el éxito es inútil","El trabajo no sirve de nada"],
    ans:1, exp:"La idea es que, además del deseo, hace falta esfuerzo. La respuesta correcta lo dice con otras palabras." },
  { id:"v_par_3", domain:"verbal", topic:"parafrasis", dif:2,
    stem:"La verdad, aunque incómoda, siempre es preferible a una mentira agradable.",
    q:"¿Cuál opción dice lo mismo con otras palabras?",
    opts:["Es mejor una verdad molesta que una mentira cómoda","Las mentiras son mejores que las verdades","La verdad nunca incomoda","Hay que evitar la verdad"],
    ans:0, exp:"La respuesta correcta conserva el sentido: se prefiere la verdad incómoda a la mentira agradable." },

  /* -- Proposiciones -- */
  { id:"v_pro_1", domain:"verbal", topic:"proposiciones", dif:3,
    stem:"Toda planta necesita luz para realizar la fotosíntesis. Analice las proposiciones:\nI. Una planta sin luz no puede realizar fotosíntesis.\nII. La luz es innecesaria para las plantas.\nIII. Algunas plantas hacen fotosíntesis en total oscuridad.",
    q:"¿Cuál(es) proposición(es) se deduce(n) del texto?",
    opts:["Solo la I","Solo la II","Solo la III","La I y la III"],
    ans:0, exp:"Si toda planta necesita luz, entonces sin luz no hay fotosíntesis (I se deduce). II y III contradicen el texto." },
  { id:"v_pro_2", domain:"verbal", topic:"proposiciones", dif:3,
    stem:"Ningún ser humano puede vivir sin agua. Analice las proposiciones:\nI. El agua es indispensable para la vida humana.\nII. Algunos humanos viven sin agua.\nIII. Sin agua, un ser humano no puede sobrevivir.",
    q:"¿Cuáles proposiciones concuerdan con el texto?",
    opts:["Solo la II","La I y la III","Solo la III","La I, la II y la III"],
    ans:1, exp:"I y III reformulan el texto; II lo contradice. La respuesta es I y III." },
  { id:"v_pro_3", domain:"verbal", topic:"proposiciones", dif:2,
    stem:"Cuando sube la temperatura, el hielo se derrite. Analice las proposiciones:\nI. El calor puede transformar el hielo en agua.\nII. El hielo se mantiene sólido al subir la temperatura.\nIII. El frío derrite el hielo.",
    q:"¿Cuál proposición se deduce del texto?",
    opts:["Solo la I","Solo la II","Solo la III","La II y la III"],
    ans:0, exp:"Si al subir la temperatura el hielo se derrite, el calor lo transforma en agua (I). II y III contradicen el texto." },

  /* ===================== MATEMÁTICO ===================== */

  /* -- Aritmética -- */
  { id:"m_ari_1", domain:"math", topic:"aritmetica", dif:2,
    stem:"En una pulpería, un confite cuesta ₡75 y un chicle ₡120. Andrés compra 8 confites y 3 chicles, y paga con un billete de ₡2 000.",
    q:"¿Cuánto recibe de vuelto?",
    opts:["₡860","₡1 040","₡960","₡1 100"],
    ans:1, exp:"8 × 75 = 600 y 3 × 120 = 360; en total gasta 960. Vuelto: 2 000 − 960 = 1 040." },
  { id:"m_ari_2", domain:"math", topic:"aritmetica", dif:2,
    stem:"María leyó {{2/5}} de un libro el lunes y {{1/3}} el martes.",
    q:"¿Qué fracción del libro le falta por leer?",
    opts:["{{1/15}}","{{4/15}}","{{11/15}}","{{3/8}}"],
    ans:1, exp:"{{2/5}} + {{1/3}} = {{6/15}} + {{5/15}} = {{11/15}} leído. Falta 1 − {{11/15}} = {{4/15}}." },
  { id:"m_ari_3", domain:"math", topic:"aritmetica", dif:2, stem:"Un litro de gasolina cuesta ₡652,50. Un conductor echa 30 litros y paga con tres billetes de ₡10 000.", q:"¿Cuánto recibe de vuelto?", opts:["₡10 425","₡9 575","₡10 575","₡11 425"], ans:0, exp:"30 × 652,50 = 19 575. Vuelto: 30 000 − 19 575 = 10 425." },
  { id:"m_ari_4", domain:"math", topic:"aritmetica", dif:3, stem:"Considere la operación: 3 + 4 × 5 − 8 ÷ 2 + 2³.", q:"¿Cuál es el resultado?", opts:["27","19","35","11"], ans:0, exp:"Potencia y luego × y ÷: 2³=8, 4×5=20, 8÷2=4. Después: 3 + 20 − 4 + 8 = 27." },
  { id:"m_ari_5", domain:"math", topic:"aritmetica", dif:2,
    stem:"La temperatura en Cartago era de 12 °C al mediodía y bajó 15 °C en la madrugada.",
    q:"¿Cuál fue la temperatura en la madrugada?",
    opts:["−3 °C","3 °C","27 °C","−27 °C"],
    ans:0, exp:"Bajar 15° desde 12° es restar: 12 − 15 = −3 °C (queda bajo cero)." },

  /* -- MCM y MCD -- */
  { id:"m_mcm_1", domain:"math", topic:"mcm_mcd", dif:2,
    stem:"Dos buses salen de la misma terminal: uno cada 12 minutos y el otro cada 18 minutos. Ambos salen juntos a las 6:00 a. m.",
    q:"¿A qué hora vuelven a salir juntos por primera vez?",
    opts:["6:30 a. m.","6:36 a. m.","6:54 a. m.","7:12 a. m."],
    ans:1, exp:"Coinciden en el MCM(12, 18) = 36 minutos. 6:00 + 36 min = 6:36 a. m." },
  { id:"m_mcm_2", domain:"math", topic:"mcm_mcd", dif:3, stem:"Dos buses salen de la misma terminal: uno cada 15 minutos y otro cada 25 minutos. Ambos salen juntos a las 6:00 a. m.", q:"¿A qué hora vuelven a salir juntos por primera vez?", opts:["7:15 a. m.","6:40 a. m.","7:00 a. m.","8:00 a. m."], ans:0, exp:"Coinciden en el MCM(15, 25) = 75 minutos. 6:00 + 1 h 15 min = 7:15 a. m." },
  { id:"m_mcm_3", domain:"math", topic:"mcm_mcd", dif:2,
    stem:"Se quieren cortar dos cintas, una de 60 cm y otra de 48 cm, en pedazos iguales lo más largos posible, sin que sobre cinta.",
    q:"¿Cuánto medirá cada pedazo?",
    opts:["6 cm","12 cm","24 cm","4 cm"],
    ans:1, exp:"El pedazo más largo que divide a ambas es el MCD(60, 48) = 12 cm." },
  { id:"m_mcm_4", domain:"math", topic:"mcm_mcd", dif:3,
    stem:"El mínimo común múltiplo de dos números es 60 y uno de ellos es 15.",
    q:"¿Cuál de los siguientes podría ser el otro número?",
    opts:["8","9","12","25"],
    ans:2, exp:"MCM(15, 12) = 60. En cambio MCM(15,8)=120, MCM(15,9)=45 y MCM(15,25)=75." },

  /* -- Relaciones de orden -- */
  { id:"m_rel_1", domain:"math", topic:"relaciones_orden", dif:2,
    stem:"Cuatro amigos comparan su edad: Ana es mayor que Beto, Carlos es menor que Beto y Diana es mayor que Ana.",
    q:"¿Quién es el menor de los cuatro?",
    opts:["Ana","Beto","Carlos","Diana"],
    ans:2, exp:"Orden: Diana > Ana > Beto > Carlos. El menor es Carlos." },
  { id:"m_rel_2", domain:"math", topic:"relaciones_orden", dif:3, stem:"Se sabe que a < 0 < b y que el valor absoluto de a es mayor que el de b.", q:"¿Cuál afirmación es siempre verdadera?", opts:["a + b > 0","a + b < 0","a + b = 0","a es mayor que b"], ans:1, exp:"Como a es negativo y |a| > |b|, el negativo pesa más que el positivo: a + b < 0." },
  { id:"m_rel_3", domain:"math", topic:"relaciones_orden", dif:3, stem:"Considere los valores 0,4 ; {{3/5}} ; 0,55 ; {{2/5}} ; 0,7.", q:"¿Cuántos de ellos son mayores que {{1/2}}?", opts:["2","3","4","1"], ans:1, exp:"{{1/2}} = 0,5. Mayores: {{3/5}} (0,6), 0,55 y 0,7. Son 3 (0,4 y {{2/5}}=0,4 no superan 0,5)." },

  /* -- Conteo intuitivo -- */
  { id:"m_cnt_1", domain:"math", topic:"conteo", dif:3,
    stem:"En una bolsa hay 5 bolas rojas, 3 azules y 4 verdes.",
    q:"¿Cuántas bolas hay que sacar como mínimo, sin ver, para asegurarse de tener al menos una de cada color?",
    opts:["3","4","10","12"],
    ans:2, exp:"En el peor caso se sacan las dos cantidades mayores (5 + 4 = 9) sin obtener el tercer color; la siguiente bola completa los tres: 10." },
  { id:"m_cnt_2", domain:"math", topic:"conteo", dif:2,
    stem:"Un candado usa un código de 2 dígitos (del 0 al 9), y se sabe que los dos dígitos son distintos.",
    q:"¿Cuántos códigos distintos son posibles?",
    opts:["81","90","100","45"],
    ans:1, exp:"El primer dígito tiene 10 opciones y el segundo 9 (distinto del primero): 10 × 9 = 90." },
  { id:"m_cnt_3", domain:"math", topic:"conteo", dif:2,
    stem:"En una reunión hay 5 personas y cada una saluda de mano a todas las demás exactamente una vez.",
    q:"¿Cuántos saludos se dan en total?",
    opts:["10","20","25","15"],
    ans:0, exp:"Cada par se saluda una vez: {{5·4/2}} = 10 saludos." },

  /* -- Permutaciones -- */
  { id:"m_per_1", domain:"math", topic:"permutaciones", dif:2,
    stem:"Tres personas van a sentarse en 3 sillas colocadas en fila.",
    q:"¿De cuántas maneras distintas pueden sentarse?",
    opts:["3","6","9","27"],
    ans:1, exp:"Ordenar 3 elementos distintos: 3! = 3·2·1 = 6." },
  { id:"m_per_2", domain:"math", topic:"permutaciones", dif:2,
    stem:"Se quieren ordenar 4 libros distintos en un estante.",
    q:"¿De cuántas maneras se pueden ordenar?",
    opts:["12","16","24","256"],
    ans:2, exp:"Ordenar 4 libros distintos son 4! (factorial): 4·3·2·1 = 24 maneras." },
  { id:"m_per_3", domain:"math", topic:"permutaciones", dif:2,
    stem:"Un equipo debe elegir un capitán y un subcapitán entre 5 jugadores.",
    q:"¿De cuántas formas distintas puede hacerlo?",
    opts:["10","20","25","120"],
    ans:1, exp:"El capitán: 5 opciones; el subcapitán: 4 restantes. 5 × 4 = 20." },

  /* -- Geometría -- */
  { id:"m_geo_1", domain:"math", topic:"geometria", dif:3,
    stem:"Un terreno rectangular mide 8 m de largo y 5 m de ancho. Se quiere cercar todo su contorno con malla, pero uno de los lados de 8 m ya tiene una pared y no necesita malla.",
    q:"¿Cuántos metros de malla se necesitan?",
    opts:["26 m","18 m","21 m","13 m"],
    ans:1, exp:"El perímetro total es 2·(8 + 5) = 26 m. Como un lado de 8 m no lleva malla: 26 − 8 = 18 m." },
  { id:"m_geo_2", domain:"math", topic:"geometria", dif:3, stem:"Una sala rectangular mide 6 m de largo por 4 m de ancho. Se cubrirá todo el piso con baldosas cuadradas de 1 m de lado, y cada baldosa cuesta ₡2 500.", q:"¿Cuánto se gasta en baldosas?", opts:["₡60 000","₡25 000","₡48 000","₡100 000"], ans:0, exp:"Área = 6 × 4 = 24 m², o sea 24 baldosas. 24 × 2 500 = 60 000." },
  { id:"m_geo_3", domain:"math", topic:"geometria", dif:3, stem:"Un terreno triangular tiene 20 m de base y 15 m de altura. Se vende a ₡8 000 el metro cuadrado.", q:"¿Cuánto cuesta el terreno?", opts:["₡1 200 000","₡2 400 000","₡150 000","₡800 000"], ans:0, exp:"Área = 20 × 15 ÷ 2 = 150 m². Costo: 150 × 8 000 = 1 200 000." },
  { id:"m_geo_4", domain:"math", topic:"geometria", dif:3,
    stem:"Una rueda tiene un radio de 35 cm. Use π ≈ {{22/7}}.",
    q:"¿Cuál es su circunferencia (perímetro)?",
    opts:["110 cm","220 cm","154 cm","440 cm"],
    ans:1, exp:"Circunferencia = 2·π·r = 2·({{22/7}})·35 = 2·22·5 = 220 cm." },

  /* -- Sucesiones -- */
  { id:"m_suc_1", domain:"math", topic:"sucesiones", dif:3, stem:"Observe la sucesión: 4, 7, 10, 13, …", q:"¿Cuál es el término que ocupa la posición 12?", opts:["37","34","40","31"], ans:0, exp:"Es aritmética con d = 3. a₁₂ = 4 + (12 − 1)·3 = 4 + 33 = 37." },
  { id:"m_suc_2", domain:"math", topic:"sucesiones", dif:2,
    stem:"En la sucesión 2, 6, 18, 54, … cada término se obtiene del anterior con la misma operación.",
    q:"¿Cuál es el siguiente término?",
    opts:["108","162","216","72"],
    ans:1, exp:"Cada término se multiplica por 3: 54 × 3 = 162." },
  { id:"m_suc_3", domain:"math", topic:"sucesiones", dif:3, stem:"Observe la sucesión: 2, 5, 10, 17, 26, …", q:"¿Cuál es el séptimo término?", opts:["50","37","42","65"], ans:0, exp:"El patrón es n²+1: 1²+1=2, 2²+1=5, … El séptimo es 7²+1 = 50." },
  { id:"m_suc_4", domain:"math", topic:"sucesiones", dif:3,
    stem:"Observe la sucesión: 2, 3, 5, 8, 12, …",
    q:"¿Cuál es el siguiente número?",
    opts:["15","16","17","18"],
    ans:2, exp:"Las diferencias aumentan: +1, +2, +3, +4. El siguiente suma +5: 12 + 5 = 17." },
  { id:"m_suc_5", domain:"math", topic:"sucesiones", dif:2,
    stem:"En la sucesión 1, 1, 2, 3, 5, 8, … cada término es la suma de los dos anteriores.",
    q:"¿Cuál es el octavo término?",
    opts:["13","21","34","19"],
    ans:1, exp:"1, 1, 2, 3, 5, 8, 13, 21. El octavo término es 21." },

  /* -- Datos y probabilidad -- */
  { id:"m_dat_1", domain:"math", topic:"datos_probabilidad", dif:2,
    stem:"En una caja hay 4 bolas rojas y 6 azules. Se saca una bola al azar.",
    q:"¿Cuál es la probabilidad de que sea roja?",
    opts:["{{2/5}}","{{3/5}}","{{4/6}}","{{1/4}}"],
    ans:0, exp:"Probabilidad = favorables ÷ total = {{4/10}} = {{2/5}}." },
  { id:"m_dat_2", domain:"math", topic:"datos_probabilidad", dif:3,
    stem:"En cuatro exámenes, un estudiante obtuvo 80, 90, 70 y 100. Hará un quinto examen y quiere que el promedio de los cinco sea exactamente 86.",
    q:"¿Qué nota necesita en el quinto examen?",
    opts:["90","86","94","100"],
    ans:0, exp:"Para promediar 86 en cinco exámenes, la suma debe ser 5 × 86 = 430. Los cuatro primeros suman 340, así que necesita 430 − 340 = 90." },
  { id:"m_dat_3", domain:"math", topic:"datos_probabilidad", dif:2,
    stem:"En una rifa hay 100 boletos: 50 sin premio, 30 con premio pequeño, 15 con premio mediano y 5 con premio mayor. Se compra un boleto.",
    q:"¿Qué resultado es el más probable?",
    opts:["Premio mayor","Premio mediano","Sin premio","Premio pequeño"],
    ans:2, exp:"El resultado más probable es el de mayor cantidad de casos: 'sin premio' (50 de 100)." },
  { id:"m_dat_4", domain:"math", topic:"datos_probabilidad", dif:3, stem:"En una bolsa hay 12 bolas: 5 rojas, 4 azules y 3 verdes. Se saca una al azar.", q:"¿Cuál es la probabilidad de que NO sea roja?", opts:["{{7/12}}","{{5/12}}","{{1/2}}","{{3/12}}"], ans:0, exp:"Las que no son rojas son 4 + 3 = 7, de 12 en total: {{7/12}}." },

  /* -- Notación algebraica -- */
  { id:"m_not_1", domain:"math", topic:"algebra_notacion", dif:2,
    stem:"Considere la frase: 'cinco más que el doble de un número'.",
    q:"¿Cuál expresión la representa?",
    opts:["2x + 5","2(x + 5)","5 − 2x","x/2 + 5"],
    ans:0, exp:"El doble del número es 2x; cinco más que eso es 2x + 5." },
  { id:"m_not_2", domain:"math", topic:"algebra_notacion", dif:2,
    stem:"Carlos tiene x colones y Ana tiene el triple que Carlos, menos 200 colones.",
    q:"¿Cuánto tiene Ana, en colones?",
    opts:["3x − 200","3(x − 200)","x/3 − 200","200 − 3x"],
    ans:0, exp:"El triple de Carlos es 3x; menos 200 es 3x − 200." },
  { id:"m_not_3", domain:"math", topic:"algebra_notacion", dif:3, stem:"Un número se representa con la letra n.", q:"¿Cuál expresión representa: el doble de un número, disminuido en cinco, es igual a quince?", opts:["2n − 5 = 15","2(n − 5) = 15","n/2 − 5 = 15","5 − 2n = 15"], ans:0, exp:"El doble del número es 2n; disminuido en 5 es 2n − 5; igual a quince: 2n − 5 = 15." },

  /* -- Relaciones algebraicas y paridad -- */
  { id:"m_alr_1", domain:"math", topic:"algebra_relaciones", dif:3, stem:"Sea n un número entero cualquiera.", q:"¿Cuál de las siguientes expresiones es múltiplo de 4 para todo n?", opts:["4n","2n","4n + 2","n + 4"], ans:0, exp:"4n = 4·n siempre es múltiplo de 4. 2n no (si n es impar), 4n+2 deja residuo 2 y n+4 depende de n." },
  { id:"m_alr_2", domain:"math", topic:"algebra_relaciones", dif:3,
    stem:"Sean P y Q enteros positivos. Se sabe que el producto P·Q es impar.",
    q:"¿Qué se puede afirmar con certeza?",
    opts:["P es par","Q es par","P y Q son impares","P es impar y Q es par"],
    ans:2, exp:"Un producto es impar solo si ambos factores son impares. Por tanto, P y Q son impares." },
  { id:"m_alr_3", domain:"math", topic:"algebra_relaciones", dif:3, stem:"Se sabe que 2x − 3 = 11.", q:"¿Cuánto vale x²?", opts:["49","14","7","21"], ans:0, exp:"De 2x − 3 = 11 se obtiene 2x = 14, o sea x = 7. Entonces x² = 7² = 49." },

  /* -- Unidades de medida -- */
  { id:"m_uni_1", domain:"math", topic:"unidades_medida", dif:2,
    stem:"Un atleta corre 5 km en 25 minutos a ritmo constante.",
    q:"¿Cuántos metros recorre en 5 minutos?",
    opts:["500 m","1000 m","1500 m","200 m"],
    ans:1, exp:"5 km = 5000 m en 25 min → 200 m por minuto. En 5 min: 200 × 5 = 1000 m." },
  { id:"m_uni_2", domain:"math", topic:"unidades_medida", dif:3, stem:"Una llave llena un balde de 18 litros en 3 minutos, a ritmo constante.", q:"¿Cuántos litros echa en 50 segundos?", opts:["5 litros","6 litros","3 litros","9 litros"], ans:0, exp:"3 min = 180 s, así que echa 18 ÷ 180 = 0,1 L por segundo. En 50 s: 50 × 0,1 = 5 litros." },
  { id:"m_uni_3", domain:"math", topic:"unidades_medida", dif:3,
    stem:"Un carro viaja a 90 km/h.",
    q:"¿Qué distancia recorre en 40 minutos?",
    opts:["36 km","60 km","120 km","45 km"],
    ans:1, exp:"40 min = {{40/60}} h = {{2/3}} h. Distancia = 90 · {{2/3}} = 60 km." },
  { id:"m_uni_4", domain:"math", topic:"unidades_medida", dif:2,
    stem:"Un evento empezó a las 10:45 a. m. y duró 2 horas y 50 minutos.",
    q:"¿A qué hora terminó?",
    opts:["12:35 p. m.","1:35 p. m.","1:25 p. m.","12:55 p. m."],
    ans:1, exp:"10:45 + 2 h = 12:45; + 50 min = 13:35, es decir 1:35 p. m." },

  /* -- Razón y proporción -- */
  { id:"m_raz_1", domain:"math", topic:"razon_proporcion", dif:2,
    stem:"En una receta, por cada 2 tazas de arroz se usan 3 tazas de agua.",
    q:"Si se usan 8 tazas de arroz, ¿cuántas tazas de agua se necesitan?",
    opts:["9","12","16","6"],
    ans:1, exp:"Proporción directa: 8 tazas son 4 veces 2, así que el agua es 4 × 3 = 12 tazas." },
  { id:"m_raz_2", domain:"math", topic:"razon_proporcion", dif:3, stem:"En un mapa, 2 cm representan 50 km reales. Dos ciudades aparecen separadas por 7 cm en el mapa.", q:"¿Qué distancia real las separa?", opts:["175 km","100 km","350 km","125 km"], ans:0, exp:"Si 2 cm = 50 km, entonces 1 cm = 25 km. Por lo tanto 7 × 25 = 175 km." },
  { id:"m_raz_3", domain:"math", topic:"razon_proporcion", dif:3,
    stem:"Tres obreros construyen un muro en 12 días.",
    q:"¿Cuántos días tardarían 6 obreros trabajando al mismo ritmo?",
    opts:["24","6","18","4"],
    ans:1, exp:"Proporción inversa: 3·12 = 36 obrero-días. Con 6 obreros: 36 ÷ 6 = 6 días." },
  { id:"m_raz_4", domain:"math", topic:"razon_proporcion", dif:3, stem:"Seis obreros tardan 10 días en terminar una obra.", q:"¿Cuántos días tardarían 4 obreros, trabajando al mismo ritmo?", opts:["15 días","6,7 días","12 días","20 días"], ans:0, exp:"Proporción inversa: 6 × 10 = 60 obrero-días. Con 4 obreros: 60 ÷ 4 = 15 días." }
];

/* Índice por tema (se llena al cargar) */
window.PAA_QUESTIONS_BY_TOPIC = window.PAA_QUESTIONS.reduce((m, q) => {
  (m[q.topic] = m[q.topic] || []).push(q);
  return m;
}, {});
