/* ============================================================
   PAASAU — Banco de preguntas EXTRA (originales, estilo PAA UCR/UNA 2026)
   Se suman al banco base de questions.js. Mismo esquema:
   { id, domain:'verbal'|'math', topic, dif:1|2|3, stem, q, opts:[a,b,c,d],
     ans:índice 0-3, exp }
   Formato 2026: 4 opciones (A-D), una sola correcta.
   Son preguntas NUEVAS, no copiadas de ningún folleto: material fresco.
   ============================================================ */
window.PAA_QUESTIONS_EXTRA = [

  /* ===================== VERBAL ===================== */

  /* -- Finalidad -- */
  { id:"v_fin_4", domain:"verbal", topic:"finalidad", dif:2,
    stem:"La municipalidad colocó basureros de reciclaje en cada parque con el fin de separar mejor los desechos.",
    q:"Según el texto, ¿cuál es la finalidad de los basureros de reciclaje?",
    opts:["Embellecer los parques","Separar mejor los desechos","Dar empleo a recolectores","Reducir el tamaño de los parques"],
    ans:1, exp:"El texto lo dice: se colocan 'con el fin de separar mejor los desechos'. Esa es la finalidad; lo demás no aparece como propósito." },
  { id:"v_fin_5", domain:"verbal", topic:"finalidad", dif:2,
    stem:"Antes de salir de viaje, Lucía anotó en una lista todo lo que debía llevar para no olvidar nada.",
    q:"¿Cuál es la finalidad de hacer la lista?",
    opts:["Presumir su organización","Evitar olvidar lo necesario","Gastar menos dinero","Llegar más rápido"],
    ans:1, exp:"El para qué de la lista es 'no olvidar nada': evitar olvidar lo necesario." },
  { id:"v_fin_6", domain:"verbal", topic:"finalidad", dif:3,
    stem:"El gobierno reduce los impuestos a los carros eléctricos para incentivar su compra y disminuir la contaminación.",
    q:"¿Cuál es la finalidad de reducir esos impuestos?",
    opts:["Recaudar más dinero","Promover vehículos menos contaminantes","Encarecer los carros de gasolina","Construir más carreteras"],
    ans:1, exp:"El propósito es incentivar la compra de carros eléctricos y bajar la contaminación: promover vehículos menos contaminantes." },
  { id:"v_fin_7", domain:"verbal", topic:"finalidad", dif:1,
    stem:"Pedro madruga todos los días para llegar temprano al trabajo.",
    q:"¿Cuál es la finalidad de que Pedro madrugue?",
    opts:["Dormir más","Llegar temprano al trabajo","Hacer ejercicio","Saltarse el desayuno"],
    ans:1, exp:"Madruga 'para llegar temprano al trabajo': esa es la finalidad." },

  /* -- Comportamiento -- */
  { id:"v_com_4", domain:"verbal", topic:"comportamiento", dif:2,
    stem:"Cuando alguien lo contradice, Daniel sube la voz y no deja hablar a los demás.",
    q:"¿Cómo se comporta Daniel ante quien lo contradice?",
    opts:["Escucha con atención","Reacciona de forma intolerante","Cambia de opinión","Se queda callado"],
    ans:1, exp:"Subir la voz e impedir que otros hablen es una reacción intolerante." },
  { id:"v_com_5", domain:"verbal", topic:"comportamiento", dif:2,
    stem:"Ante un examen difícil, Sofía respira, lee con calma y resuelve primero lo que sabe.",
    q:"¿Cómo se comporta Sofía frente al examen difícil?",
    opts:["Se bloquea por los nervios","Actúa con calma y estrategia","Abandona el examen","Copia a sus compañeros"],
    ans:1, exp:"Respirar, leer con calma y empezar por lo conocido describe una conducta calmada y estratégica." },
  { id:"v_com_6", domain:"verbal", topic:"comportamiento", dif:1,
    stem:"El perro mueve la cola y salta cada vez que su dueño llega a casa.",
    q:"¿Cómo se comporta el perro cuando llega su dueño?",
    opts:["Muestra alegría","Se esconde con miedo","Ladra con enojo","Se queda dormido"],
    ans:0, exp:"Mover la cola y saltar al llegar el dueño expresa alegría." },
  { id:"v_com_7", domain:"verbal", topic:"comportamiento", dif:2,
    stem:"Cada vez que pierde un partido, el jugador felicita al rival y agradece a su equipo.",
    q:"¿Cómo se comporta el jugador ante la derrota?",
    opts:["Con resentimiento","Con deportividad","Con indiferencia","Con desesperación"],
    ans:1, exp:"Felicitar al rival y agradecer al equipo tras perder es actuar con deportividad." },

  /* -- Causa y consecuencia -- */
  { id:"v_cau_5", domain:"verbal", topic:"causa_consecuencia", dif:2,
    stem:"Como no regaron las plantas durante semanas, el jardín se secó.",
    q:"Según el texto, ¿cuál fue la causa de que el jardín se secara?",
    opts:["El exceso de agua","La falta de riego","El frío del invierno","La sombra de los árboles"],
    ans:1, exp:"El conector 'como' introduce la causa: no regar las plantas (falta de riego)." },
  { id:"v_cau_6", domain:"verbal", topic:"causa_consecuencia", dif:2,
    stem:"El aumento del precio del combustible provocó que muchos productos se encarecieran.",
    q:"Según el texto, ¿cuál es una consecuencia del aumento del combustible?",
    opts:["Los productos bajaron de precio","Muchos productos se encarecieron","El combustible se agotó","Los salarios subieron"],
    ans:1, exp:"El efecto que 'provocó' el aumento del combustible fue que los productos se encarecieran." },
  { id:"v_cau_7", domain:"verbal", topic:"causa_consecuencia", dif:2,
    stem:"Gracias a que estudió con constancia todo el año, Karla aprobó el examen de admisión.",
    q:"¿Cuál fue la causa de que Karla aprobara?",
    opts:["La suerte","El estudio constante","La facilidad del examen","La ayuda de sus amigos"],
    ans:1, exp:"'Gracias a que estudió con constancia' señala la causa del resultado." },
  { id:"v_cau_8", domain:"verbal", topic:"causa_consecuencia", dif:3,
    stem:"La tala de las montañas dejó el suelo sin raíces que lo sostuvieran; por eso, con las lluvias, ocurrieron deslizamientos.",
    q:"Según el texto, ¿cuál es la causa de los deslizamientos?",
    opts:["Las lluvias por sí solas","La tala que debilitó el suelo","La construcción de casas","La falta de lluvia"],
    ans:1, exp:"El texto encadena: la tala dejó el suelo sin raíces y 'por eso' hubo deslizamientos. La causa de fondo es la tala." },
  { id:"v_cau_9", domain:"verbal", topic:"causa_consecuencia", dif:2,
    stem:"El uso responsable del agua permite que haya reservas durante la época seca.",
    q:"¿Qué relación de causa y consecuencia plantea el texto?",
    opts:["Cuidar el agua asegura reservas para la sequía","La sequía produce más agua","El agua no se puede almacenar","La época seca no afecta a nadie"],
    ans:0, exp:"La causa (usar el agua de forma responsable) tiene como consecuencia tener reservas en la época seca." },

  /* -- Simple y complejo -- */
  { id:"v_sim_4", domain:"verbal", topic:"simple_complejo", dif:2,
    stem:"Encender una vela requiere solo un fósforo; en cambio, poner en marcha una central eléctrica implica turbinas, controles y un equipo de ingenieros.",
    q:"¿En qué se diferencian ambas acciones?",
    opts:["En su antigüedad","En la cantidad de elementos y procesos","En su color","En su precio"],
    ans:1, exp:"El contraste es entre algo de un solo paso (simple) y algo de muchos componentes y procesos (complejo)." },
  { id:"v_sim_5", domain:"verbal", topic:"simple_complejo", dif:2,
    stem:"Un triciclo tiene pocas piezas fáciles de armar; un automóvil moderno integra miles de componentes mecánicos y electrónicos.",
    q:"¿Cómo es el automóvil frente al triciclo?",
    opts:["Más simple","Más complejo","Más lento","Más barato"],
    ans:1, exp:"Por su gran cantidad de componentes, el automóvil se presenta como más complejo." },
  { id:"v_sim_6", domain:"verbal", topic:"simple_complejo", dif:1,
    stem:"Saludar con la mano es un gesto de un solo movimiento, fácil de hacer.",
    q:"¿Cómo se describe ese gesto?",
    opts:["Complejo","Simple","Costoso","Peligroso"],
    ans:1, exp:"Un gesto de un solo movimiento y fácil es simple." },
  { id:"v_sim_7", domain:"verbal", topic:"simple_complejo", dif:3,
    stem:"Freír un huevo tiene básicamente un paso; organizar un banquete de varios tiempos exige planear, coordinar y cocinar decenas de platos a la vez.",
    q:"El banquete, frente al huevo frito, se presenta como algo:",
    opts:["Igual de simple","Más complejo","Menos nutritivo","Más rápido"],
    ans:1, exp:"El banquete reúne muchas tareas interrelacionadas: es más complejo que la acción de un solo paso." },

  /* -- Conceptualización -- */
  { id:"v_con_5", domain:"verbal", topic:"conceptualizacion", dif:2,
    stem:"Encontró una billetera con dinero y la devolvió completa a su dueño, aunque nadie lo habría sabido.",
    q:"¿Qué palabra describe su actitud?",
    opts:["Honradez","Astucia","Timidez","Indiferencia"],
    ans:0, exp:"Devolver lo ajeno aun sin ser visto se resume en el concepto de honradez." },
  { id:"v_con_6", domain:"verbal", topic:"conceptualizacion", dif:2,
    stem:"Trabajó horas extra, sin quejarse, para entregar el proyecto en la fecha acordada.",
    q:"¿Cómo se describe, en una palabra, su actitud?",
    opts:["Pereza","Compromiso","Vanidad","Suerte"],
    ans:1, exp:"Esforzarse para cumplir lo acordado refleja compromiso." },
  { id:"v_con_7", domain:"verbal", topic:"conceptualizacion", dif:2,
    stem:"Escuchó el problema de su amiga y se puso en su lugar para comprender lo que sentía.",
    q:"¿Qué palabra resume esa actitud?",
    opts:["Empatía","Envidia","Curiosidad","Orgullo"],
    ans:0, exp:"Ponerse en el lugar del otro para comprender lo que siente es empatía." },
  { id:"v_con_8", domain:"verbal", topic:"conceptualizacion", dif:2,
    stem:"No presumió de sus logros y reconoció abiertamente la ayuda de los demás.",
    q:"¿Cómo se caracteriza, en una palabra, a esta persona?",
    opts:["Soberbia","Humildad","Frialdad","Pereza"],
    ans:1, exp:"No presumir y reconocer la ayuda ajena describe humildad." },
  { id:"v_con_9", domain:"verbal", topic:"conceptualizacion", dif:3,
    stem:"Siguió intentando resolver el problema, sin perder la calma, aunque ya había fallado diez veces.",
    q:"¿Qué palabra resume su actitud?",
    opts:["Tenacidad","Pereza","Suerte","Distracción"],
    ans:0, exp:"Insistir con calma pese a los fracasos repetidos se conceptualiza como tenacidad." },

  /* -- Orden y desorden -- */
  { id:"v_ord_4", domain:"verbal", topic:"orden_desorden", dif:2,
    stem:"El taller estaba lleno de herramientas tiradas por el suelo; tras la limpieza, cada una quedó colgada en su gancho rotulado.",
    q:"¿Qué cambio experimentó el taller?",
    opts:["Del orden al desorden","Del desorden al orden","De lo nuevo a lo viejo","De lo grande a lo pequeño"],
    ans:1, exp:"Pasó de herramientas tiradas (desorden) a cada una en su lugar rotulado (orden)." },
  { id:"v_ord_5", domain:"verbal", topic:"orden_desorden", dif:1,
    stem:"En la biblioteca, los libros están clasificados por autor y por tema.",
    q:"¿Cómo puede describirse esa biblioteca?",
    opts:["Ordenada","Desordenada","Vacía","Sucia"],
    ans:0, exp:"Que los libros estén clasificados por criterios describe una biblioteca ordenada." },
  { id:"v_ord_6", domain:"verbal", topic:"orden_desorden", dif:2,
    stem:"Después de la fiesta, platos, vasos y sillas quedaron regados por toda la casa.",
    q:"¿Cómo quedó la casa?",
    opts:["En orden","En desorden","Limpia","Vacía"],
    ans:1, exp:"Cosas regadas por todas partes describen desorden." },
  { id:"v_ord_7", domain:"verbal", topic:"orden_desorden", dif:3,
    stem:"El archivo digital pasó de carpetas sin nombre y documentos sueltos a un sistema con categorías claras y bien rotuladas.",
    q:"¿Qué describe ese cambio?",
    opts:["Un aumento del desorden","Una organización del desorden previo","Una pérdida de archivos","Un cambio de colores"],
    ans:1, exp:"Pasar de documentos sueltos a categorías claras es organizar lo que estaba en desorden." },

  /* -- Orden temporal -- */
  { id:"v_tmp_4", domain:"verbal", topic:"orden_temporal", dif:2,
    stem:"Primero se lava la ropa, luego se tiende, después se plancha y, por último, se guarda.",
    q:"Según el texto, ¿qué se hace inmediatamente antes de guardar la ropa?",
    opts:["Tenderla","Plancharla","Lavarla","Comprarla"],
    ans:1, exp:"La secuencia es lavar → tender → planchar → guardar. Justo antes de guardar se plancha." },
  { id:"v_tmp_5", domain:"verbal", topic:"orden_temporal", dif:1,
    stem:"Ana se baña, se viste y luego desayuna.",
    q:"¿Qué hace Ana justo antes de desayunar?",
    opts:["Bañarse","Vestirse","Dormir","Salir"],
    ans:1, exp:"El orden es bañarse → vestirse → desayunar. Antes de desayunar, se viste." },
  { id:"v_tmp_6", domain:"verbal", topic:"orden_temporal", dif:2,
    stem:"El albañil mezcla el cemento, levanta la pared y, al final, la pinta.",
    q:"¿Qué ocurre después de levantar la pared?",
    opts:["Mezclar el cemento","Pintarla","Comprar ladrillos","Cavar la zanja"],
    ans:1, exp:"La secuencia es mezclar → levantar → pintar. Después de levantar la pared, se pinta." },
  { id:"v_tmp_7", domain:"verbal", topic:"orden_temporal", dif:3,
    stem:"En la función: se abren las cortinas, se presenta el primer acto, hay un intermedio y luego viene el segundo acto.",
    q:"¿Qué ocurre inmediatamente antes del segundo acto?",
    opts:["El primer acto","El intermedio","La apertura de cortinas","Los aplausos finales"],
    ans:1, exp:"La secuencia es cortinas → primer acto → intermedio → segundo acto. Justo antes del segundo acto está el intermedio." },

  /* -- Esencia -- */
  { id:"v_ese_4", domain:"verbal", topic:"esencia", dif:3,
    stem:"Lo propio de un buen médico es escuchar al paciente, examinarlo con cuidado y recetar lo apropiado.",
    q:"De acuerdo con la lógica del texto, ¿qué sería propio de un buen mecánico?",
    opts:["Escuchar al cliente, revisar el vehículo y reparar lo necesario","Cobrar lo más posible","Cambiar todas las piezas siempre","Trabajar sin revisar nada"],
    ans:0, exp:"Por lógica paralela, las tres acciones del médico (escuchar, examinar, dar lo apropiado) se trasladan al mecánico: escuchar, revisar y reparar lo necesario." },
  { id:"v_ese_5", domain:"verbal", topic:"esencia", dif:2,
    stem:"Una característica esencial del hielo es estar frío y en estado sólido.",
    q:"Según el texto, ¿cuál es una característica esencial del hielo?",
    opts:["Su precio","Estar frío y sólido","Su tamaño","Su marca"],
    ans:1, exp:"Lo propio del hielo, según el texto, es estar frío y sólido." },
  { id:"v_ese_6", domain:"verbal", topic:"esencia", dif:3,
    stem:"Lo propio de un reloj es marcar el paso del tiempo.",
    q:"Por la misma lógica, ¿qué es lo propio de un termómetro?",
    opts:["Marcar la hora","Medir la temperatura","Pesar objetos","Medir distancias"],
    ans:1, exp:"Si lo propio del reloj es medir el tiempo, lo propio del termómetro es medir la temperatura." },
  { id:"v_ese_7", domain:"verbal", topic:"esencia", dif:2,
    stem:"Lo esencial de una llave es abrir y cerrar una cerradura determinada.",
    q:"Según el texto, ¿qué es lo propio de una llave?",
    opts:["Su color","Abrir y cerrar su cerradura","Su material","Su tamaño"],
    ans:1, exp:"Lo característico de una llave es su función: abrir y cerrar su cerradura." },

  /* -- Perspectiva -- */
  { id:"v_per_4", domain:"verbal", topic:"perspectiva", dif:2,
    stem:"El mismo invierno que entristece al turista alegra al dueño de la tienda de abrigos.",
    q:"¿Qué muestra esta diferencia?",
    opts:["Que el invierno es siempre malo","Que un mismo hecho se valora distinto según quién lo viva","Que el turista tiene razón","Que nadie disfruta el invierno"],
    ans:1, exp:"Un mismo hecho (el invierno) se valora de modo distinto según la perspectiva de cada quien." },
  { id:"v_per_5", domain:"verbal", topic:"perspectiva", dif:2,
    stem:"Para el niño, la montaña es un lugar de aventura; para el anciano, un esfuerzo agotador.",
    q:"¿Qué idea expresa el texto?",
    opts:["La montaña no debe visitarse","La misma montaña se percibe distinto según la persona","Los niños no se cansan","Los ancianos no caminan"],
    ans:1, exp:"La valoración depende del observador: niño y anciano viven la misma montaña de modo distinto." },
  { id:"v_per_6", domain:"verbal", topic:"perspectiva", dif:3,
    stem:"Reprobar un examen puede verse como un fracaso o como una oportunidad para descubrir qué reforzar.",
    q:"¿Qué plantea el texto?",
    opts:["Que reprobar no tiene solución","Que un mismo hecho admite distintas lecturas","Que los exámenes son injustos","Que nadie aprende de los errores"],
    ans:1, exp:"El mismo hecho (reprobar) se interpreta de dos formas según la mirada: admite distintas lecturas." },
  { id:"v_per_7", domain:"verbal", topic:"perspectiva", dif:2,
    stem:"Lo que para una persona es música a buen volumen, para la vecina puede ser un ruido molesto.",
    q:"¿Qué idea expresa el texto?",
    opts:["La música siempre molesta","Un mismo sonido se valora distinto según quién lo escuche","Nadie debe oír música","La vecina tiene mal gusto"],
    ans:1, exp:"El mismo sonido se percibe distinto según quién lo escuche: es cuestión de perspectiva." },
  { id:"v_per_8", domain:"verbal", topic:"perspectiva", dif:2,
    stem:"El mismo comentario directo puede parecer sincero a unos y grosero a otros.",
    q:"¿Qué expresa el texto?",
    opts:["Que hay que mentir siempre","Que la interpretación depende de quién recibe el mensaje","Que nadie debe opinar","Que la sinceridad es grosera"],
    ans:1, exp:"Un mismo comentario se interpreta distinto según quién lo reciba: depende de la perspectiva." },

  /* -- Idea implícita -- */
  { id:"v_imp_6", domain:"verbal", topic:"idea_implicita", dif:2,
    stem:"Cada vez que come en ese restaurante, a Luis le duele el estómago.",
    q:"¿Cuál es una idea implícita en el texto?",
    opts:["A Luis no le gusta comer","Algo de esa comida le hace daño","El restaurante es caro","Luis nunca come"],
    ans:1, exp:"Que siempre le duela el estómago tras comer ahí implica que algo de esa comida le cae mal." },
  { id:"v_imp_7", domain:"verbal", topic:"idea_implicita", dif:2,
    stem:"La biblioteca siempre se llena durante la época de exámenes.",
    q:"¿Cuál es una idea implícita?",
    opts:["La biblioteca es muy pequeña","En época de exámenes la gente estudia más","Nadie usa la biblioteca","Los libros son gratis"],
    ans:1, exp:"Si se llena justo en exámenes, se infiere que en esa época la gente estudia más." },
  { id:"v_imp_8", domain:"verbal", topic:"idea_implicita", dif:2,
    stem:"Antes de salir, Juan tomó paraguas, botas de hule y un abrigo grueso.",
    q:"¿Qué idea está implícita en el texto?",
    opts:["Iba a una fiesta","Esperaba mal tiempo","Vendía ropa","Hacía mucho calor"],
    ans:1, exp:"Llevar paraguas, botas y abrigo implica que esperaba lluvia y frío: mal tiempo." },
  { id:"v_imp_9", domain:"verbal", topic:"idea_implicita", dif:1,
    stem:"Las luces de la casa estaban apagadas y nadie respondió a la puerta.",
    q:"¿Qué idea está implícita?",
    opts:["La casa estaba en venta","Probablemente no había nadie","Había una fiesta adentro","Era de día"],
    ans:1, exp:"Luces apagadas y nadie que responda sugieren que, probablemente, no había nadie en casa." },
  { id:"v_imp_10", domain:"verbal", topic:"idea_implicita", dif:2,
    stem:"Marta revisa tres veces que la puerta esté cerrada antes de dormir.",
    q:"¿Cuál es una idea implícita?",
    opts:["Marta es descuidada","Marta es precavida con la seguridad","Marta no duerme nunca","La puerta está rota"],
    ans:1, exp:"Revisar varias veces la cerradura sugiere que Marta es precavida con la seguridad." },
  { id:"v_imp_11", domain:"verbal", topic:"idea_implicita", dif:3,
    stem:"Aunque le ofrecieron más sueldo en otra empresa, decidió quedarse donde estaba.",
    q:"¿Qué idea está implícita?",
    opts:["El dinero es lo único que le importa","Valora algo más que el salario","No sabe tomar decisiones","La otra empresa cerró"],
    ans:1, exp:"Rechazar más sueldo para quedarse implica que valora algo más que el dinero (ambiente, estabilidad, etc.)." },

  /* -- Idea principal / tema -- */
  { id:"v_pri_4", domain:"verbal", topic:"idea_principal", dif:2,
    stem:"El reciclaje reduce la basura, ahorra recursos naturales y disminuye la contaminación.",
    q:"¿Cuál es la idea principal del texto?",
    opts:["Los beneficios del reciclaje","La historia de la basura","El precio de los recursos","La contaminación del aire"],
    ans:0, exp:"Los tres puntos enumeran ventajas: la idea general es los beneficios del reciclaje." },
  { id:"v_pri_5", domain:"verbal", topic:"idea_principal", dif:2,
    stem:"Las abejas polinizan cultivos, producen miel y ayudan a mantener el equilibrio de muchos ecosistemas.",
    q:"¿Cuál es el tema central del texto?",
    opts:["La importancia de las abejas","El sabor de la miel","El tamaño de las abejas","El peligro de las abejas"],
    ans:0, exp:"Los tres rasgos apuntan a un mismo tema: la importancia de las abejas." },
  { id:"v_pri_6", domain:"verbal", topic:"idea_principal", dif:2,
    stem:"Leer mejora el vocabulario, ejercita la memoria y abre la mente a nuevas ideas.",
    q:"¿Cuál es la idea principal?",
    opts:["Los beneficios de la lectura","El precio de los libros","La dificultad de leer","La historia de la escritura"],
    ans:0, exp:"El texto enumera ventajas de leer: su idea general son los beneficios de la lectura." },
  { id:"v_pri_7", domain:"verbal", topic:"idea_principal", dif:3,
    stem:"El río nace en la montaña, cruza el valle dando agua a los cultivos y desemboca en el mar, sosteniendo la vida a su paso.",
    q:"¿Cuál es el tema central del texto?",
    opts:["El color del agua","El recorrido del río y su aporte a la vida","La altura de la montaña","La pesca en el mar"],
    ans:1, exp:"Todo el texto sigue el recorrido del río y lo que aporta: ese es el tema central." },
  { id:"v_pri_8", domain:"verbal", topic:"idea_principal", dif:2,
    stem:"Dormir bien mejora la memoria, fortalece las defensas y estabiliza el estado de ánimo.",
    q:"¿Cuál es la idea principal?",
    opts:["La importancia de dormir bien","Los tipos de camas","Las horas de trabajo","Las pesadillas comunes"],
    ans:0, exp:"Los beneficios enumerados apuntan a la importancia de dormir bien." },
  { id:"v_pri_9", domain:"verbal", topic:"idea_principal", dif:3,
    stem:"En Costa Rica conviven el español, el bribri y el inglés criollo limonense, reflejo de su diversidad cultural.",
    q:"¿Cuál es el tema central del texto?",
    opts:["La diversidad lingüística de Costa Rica","La gramática del español","La población de Limón","La enseñanza del inglés"],
    ans:0, exp:"El texto usa las tres lenguas como muestra de la diversidad cultural y lingüística del país." },

  /* -- Paráfrasis -- */
  { id:"v_par_4", domain:"verbal", topic:"parafrasis", dif:2,
    stem:"Quien mucho abarca, poco aprieta.",
    q:"¿Cuál opción expresa la misma idea con otras palabras?",
    opts:["Querer hacer demasiado a la vez impide hacerlo bien","Hay que trabajar mucho siempre","Apretar las cosas es difícil","Nunca conviene intentar nada"],
    ans:0, exp:"El refrán dice que intentar demasiado a la vez impide lograrlo bien: eso reformula la opción correcta." },
  { id:"v_par_5", domain:"verbal", topic:"parafrasis", dif:2,
    stem:"El esfuerzo de hoy es la recompensa de mañana.",
    q:"¿Cuál opción dice lo mismo con otras palabras?",
    opts:["El trabajo nunca sirve","Lo que se trabaja ahora da frutos después","El mañana no importa","La recompensa llega sin esfuerzo"],
    ans:1, exp:"La idea es que el esfuerzo presente rinde frutos en el futuro." },
  { id:"v_par_6", domain:"verbal", topic:"parafrasis", dif:2,
    stem:"No todo lo que brilla es oro.",
    q:"¿Cuál opción conserva el sentido del texto?",
    opts:["El oro siempre brilla","Las apariencias pueden engañar","Todo lo brillante es valioso","El oro nunca brilla"],
    ans:1, exp:"El refrán advierte que la apariencia no garantiza el valor: las apariencias pueden engañar." },
  { id:"v_par_7", domain:"verbal", topic:"parafrasis", dif:3,
    stem:"La libertad de uno termina donde empieza la del otro.",
    q:"¿Cuál opción expresa la misma idea?",
    opts:["Nadie es realmente libre","La libertad propia tiene como límite la de los demás","La libertad no tiene ningún límite","Solo una persona puede ser libre"],
    ans:1, exp:"La frase dice que mi libertad llega hasta donde empieza la del otro: tiene como límite la libertad ajena." },
  { id:"v_par_8", domain:"verbal", topic:"parafrasis", dif:2,
    stem:"Más vale prevenir que lamentar.",
    q:"¿Cuál opción reproduce la idea del texto?",
    opts:["Lamentarse es lo más útil","Es mejor tomar precauciones a tiempo que sufrir después","Nunca pasa nada malo","Prevenir es imposible"],
    ans:1, exp:"El refrán recomienda anticiparse: precaver a tiempo es preferible a lamentar luego." },

  /* -- Proposiciones -- */
  { id:"v_pro_4", domain:"verbal", topic:"proposiciones", dif:3,
    stem:"Todos los metales conducen la electricidad. Analice las proposiciones:\nI. El cobre, que es un metal, conduce electricidad.\nII. Ningún metal conduce electricidad.\nIII. Hay metales que no conducen electricidad.",
    q:"¿Cuál(es) proposición(es) se deduce(n) del texto?",
    opts:["Solo la I","Solo la II","La II y la III","Las tres"],
    ans:0, exp:"Si todos los metales conducen, el cobre (metal) conduce: I se deduce. II y III contradicen el texto." },
  { id:"v_pro_5", domain:"verbal", topic:"proposiciones", dif:3,
    stem:"Toda persona inscrita debe presentar su cédula. Analice las proposiciones:\nI. Quien no presenta la cédula no cumple lo exigido.\nII. La cédula es opcional.\nIII. Una persona inscrita sin cédula no cumple el requisito.",
    q:"¿Cuáles proposiciones concuerdan con el texto?",
    opts:["Solo la II","La I y la III","Solo la III","Las tres"],
    ans:1, exp:"I y III reformulan la obligación de presentar cédula; II la contradice." },
  { id:"v_pro_6", domain:"verbal", topic:"proposiciones", dif:2,
    stem:"Cuando llueve, la cancha se moja. Analice las proposiciones:\nI. La lluvia moja la cancha.\nII. La cancha se moja sola, sin lluvia.\nIII. La lluvia seca la cancha.",
    q:"¿Cuál proposición se deduce del texto?",
    opts:["Solo la I","Solo la II","Solo la III","La I y la III"],
    ans:0, exp:"El texto dice que la lluvia moja la cancha: I se deduce. II y III no se siguen del texto." },
  { id:"v_pro_7", domain:"verbal", topic:"proposiciones", dif:3,
    stem:"Ningún estudiante aprobó sin entregar el proyecto. Analice las proposiciones:\nI. Entregar el proyecto fue necesario para aprobar.\nII. Algún estudiante aprobó sin entregar el proyecto.\nIII. Quien no entregó el proyecto no aprobó.",
    q:"¿Cuáles proposiciones se deducen del texto?",
    opts:["Solo la I","La I y la III","Solo la II","Las tres"],
    ans:1, exp:"'Ninguno aprobó sin entregar' equivale a que entregar era necesario (I) y a que quien no entregó no aprobó (III). II lo contradice." },
  { id:"v_pro_8", domain:"verbal", topic:"proposiciones", dif:2,
    stem:"Todas las aves tienen plumas. Analice las proposiciones:\nI. El gorrión, que es un ave, tiene plumas.\nII. Existen aves sin plumas.\nIII. El gorrión no tiene plumas.",
    q:"¿Cuál proposición se deduce del texto?",
    opts:["Solo la I","Solo la II","La II y la III","Las tres"],
    ans:0, exp:"Si todas las aves tienen plumas, el gorrión (ave) las tiene: I se deduce. II y III contradicen el texto." },

  /* ===================== MATEMÁTICO ===================== */

  /* -- Aritmética -- */
  { id:"m_ari_6", domain:"math", topic:"aritmetica", dif:2,
    stem:"En una soda, un casado cuesta ₡2 500 y un fresco ₡900. Marta pide 3 casados y 2 frescos, y paga con ₡10 000.",
    q:"¿Cuánto recibe de vuelto?",
    opts:["₡600","₡700","₡800","₡900"],
    ans:1, exp:"3·2 500 = 7 500 y 2·900 = 1 800; total 9 300. Vuelto: 10 000 − 9 300 = 700." },
  { id:"m_ari_7", domain:"math", topic:"aritmetica", dif:2,
    stem:"Considere la operación: 2/3 + 1/6 − 1/2.",
    q:"¿Cuál es el resultado?",
    opts:["1/2","1/4","1/3","2/3"],
    ans:2, exp:"Con común denominador 6: 4/6 + 1/6 − 3/6 = 2/6 = 1/3." },
  { id:"m_ari_8", domain:"math", topic:"aritmetica", dif:1,
    stem:"Considere la operación: 18 − 3 × 4 + 6 ÷ 2.",
    q:"¿Cuál es el resultado?",
    opts:["15","9","21","12"],
    ans:1, exp:"Primero × y ÷: 3×4=12 y 6÷2=3. Luego 18 − 12 + 3 = 9." },
  { id:"m_ari_9", domain:"math", topic:"aritmetica", dif:2,
    stem:"En una finca hay 240 árboles y 3/8 de ellos son de naranja.",
    q:"¿Cuántos árboles de naranja hay?",
    opts:["64","80","96","90"],
    ans:3, exp:"240 ÷ 8 = 30; 30 × 3 = 90 árboles de naranja." },
  { id:"m_ari_10", domain:"math", topic:"aritmetica", dif:2,
    stem:"Considere la operación con enteros: (−6) + (−4) − (−10) + 2.",
    q:"¿Cuál es el resultado?",
    opts:["−2","0","2","−12"],
    ans:2, exp:"(−6) + (−4) = −10; −10 − (−10) = 0; 0 + 2 = 2." },

  /* -- MCM y MCD -- */
  { id:"m_mcm_5", domain:"math", topic:"mcm_mcd", dif:2,
    stem:"Dos luces parpadean: una cada 8 segundos y la otra cada 10 segundos. En este momento parpadean juntas.",
    q:"¿Dentro de cuántos segundos vuelven a parpadear juntas por primera vez?",
    opts:["18 s","40 s","80 s","20 s"],
    ans:1, exp:"Coinciden en el MCM(8, 10). 8 = 2³ y 10 = 2·5, así que MCM = 2³·5 = 40 s." },
  { id:"m_mcm_6", domain:"math", topic:"mcm_mcd", dif:1,
    stem:"Considere los números 18 y 24.",
    q:"¿Cuál es su máximo común divisor (MCD)?",
    opts:["3","6","12","72"],
    ans:1, exp:"18 = 2·3² y 24 = 2³·3. Comunes con menor exponente: 2·3 = 6." },
  { id:"m_mcm_7", domain:"math", topic:"mcm_mcd", dif:3,
    stem:"Se reparten 36 lápices y 48 cuadernos en paquetes iguales, con la mayor cantidad posible de paquetes y sin que sobre nada.",
    q:"¿Cuántos paquetes se forman?",
    opts:["6","8","12","4"],
    ans:2, exp:"La mayor cantidad de paquetes iguales es el MCD(36, 48). 36 = 2²·3² y 48 = 2⁴·3, así que MCD = 2²·3 = 12 paquetes." },

  /* -- Relaciones de orden -- */
  { id:"m_rel_4", domain:"math", topic:"relaciones_orden", dif:2,
    stem:"En una fila, Marta está delante de Luis, Luis delante de Sara y Pedro está detrás de Sara.",
    q:"¿Quién va de último en la fila?",
    opts:["Marta","Luis","Sara","Pedro"],
    ans:3, exp:"De adelante hacia atrás: Marta, Luis, Sara, Pedro. El último es Pedro." },
  { id:"m_rel_5", domain:"math", topic:"relaciones_orden", dif:2,
    stem:"Se sabe que x > y, que y > z y que z = 5.",
    q:"¿Cuál afirmación es siempre verdadera?",
    opts:["y es menor que 5","x es mayor que 5","z es el mayor","x es igual a y"],
    ans:1, exp:"Como x > y > z = 5, entonces x > 5. (y también es > 5, pero la opción dice 'menor', que es falsa.)" },
  { id:"m_rel_6", domain:"math", topic:"relaciones_orden", dif:2,
    stem:"Considere los números 0,4 ; 3/8 ; 0,45 ; 1/2.",
    q:"¿Cuál de ellos es el menor?",
    opts:["0,4","3/8","0,45","1/2"],
    ans:1, exp:"En decimales: 0,40 ; 0,375 ; 0,45 ; 0,50. El menor es 3/8 = 0,375." },
  { id:"m_rel_7", domain:"math", topic:"relaciones_orden", dif:3,
    stem:"De tres cajas, A pesa más que B, y C pesa menos que B.",
    q:"¿Cuál afirmación es correcta?",
    opts:["C es la más pesada","A es la más pesada","B es la más liviana","A y C pesan igual"],
    ans:1, exp:"Como A > B y B > C, el orden es A > B > C. La más pesada es A." },

  /* -- Conteo intuitivo -- */
  { id:"m_cnt_4", domain:"math", topic:"conteo", dif:2,
    stem:"Un menú ofrece 3 platos fuertes y 4 bebidas.",
    q:"¿Cuántas combinaciones distintas de un plato y una bebida se pueden armar?",
    opts:["7","12","9","16"],
    ans:1, exp:"Por el principio multiplicativo: 3 × 4 = 12 combinaciones." },
  { id:"m_cnt_5", domain:"math", topic:"conteo", dif:3,
    stem:"En una gaveta, a oscuras, hay 6 medias negras y 8 blancas mezcladas.",
    q:"¿Cuántas medias hay que sacar como mínimo para asegurar un par del mismo color?",
    opts:["3","4","9","2"],
    ans:0, exp:"En el peor caso se sacan 2 de distinto color; la tercera forzosamente repite color y forma un par. Mínimo: 3." },
  { id:"m_cnt_6", domain:"math", topic:"conteo", dif:2,
    stem:"Se forman placas de 3 letras distintas usando solo A, B, C y D (sin repetir letras).",
    q:"¿Cuántas placas distintas se pueden formar?",
    opts:["12","24","64","18"],
    ans:1, exp:"Primera letra: 4 opciones; segunda: 3; tercera: 2. Total 4·3·2 = 24." },
  { id:"m_cnt_7", domain:"math", topic:"conteo", dif:3,
    stem:"En una bolsa hay 5 bolas rojas y 7 azules.",
    q:"¿Cuántas bolas hay que sacar como mínimo, sin ver, para asegurar 2 rojas?",
    opts:["7","8","9","2"],
    ans:2, exp:"En el peor caso salen las 7 azules antes que rojas; luego se necesitan 2 rojas. Total 7 + 2 = 9." },

  /* -- Permutaciones -- */
  { id:"m_per_4", domain:"math", topic:"permutaciones", dif:2,
    stem:"Cinco personas se colocan en fila para una foto.",
    q:"¿De cuántas maneras distintas pueden ordenarse?",
    opts:["25","60","120","20"],
    ans:2, exp:"Ordenar 5 elementos distintos: 5! = 5·4·3·2·1 = 120." },
  { id:"m_per_5", domain:"math", topic:"permutaciones", dif:2,
    stem:"De un grupo de 6 personas se debe elegir un presidente y un secretario (cargos distintos).",
    q:"¿De cuántas formas se pueden elegir?",
    opts:["11","30","36","720"],
    ans:1, exp:"Presidente: 6 opciones; secretario: 5 restantes. Total 6 × 5 = 30." },
  { id:"m_per_6", domain:"math", topic:"permutaciones", dif:2,
    stem:"Se quieren ordenar en fila las 4 letras distintas de la palabra ROMA.",
    q:"¿Cuántos ordenamientos distintos hay?",
    opts:["12","24","16","8"],
    ans:1, exp:"Son 4 letras distintas: 4! = 4·3·2·1 = 24." },

  /* -- Geometría -- */
  { id:"m_geo_5", domain:"math", topic:"geometria", dif:2,
    stem:"Un rectángulo tiene un área de 48 cm² y su base mide 8 cm.",
    q:"¿Cuánto mide su altura?",
    opts:["6 cm","5 cm","40 cm","12 cm"],
    ans:0, exp:"Área = base × altura, así que altura = 48 ÷ 8 = 6 cm." },
  { id:"m_geo_6", domain:"math", topic:"geometria", dif:2,
    stem:"Un cuadrado tiene un perímetro de 36 cm.",
    q:"¿Cuál es su área?",
    opts:["81 cm²","36 cm²","144 cm²","324 cm²"],
    ans:0, exp:"Lado = 36 ÷ 4 = 9 cm. Área = lado² = 9² = 81 cm²." },
  { id:"m_geo_7", domain:"math", topic:"geometria", dif:2,
    stem:"Un triángulo tiene un área de 24 cm² y su base mide 6 cm.",
    q:"¿Cuánto mide su altura?",
    opts:["4 cm","8 cm","6 cm","12 cm"],
    ans:1, exp:"Área = base × altura ÷ 2, entonces 24 = 6 × altura ÷ 2 = 3·altura, así que altura = 8 cm." },
  { id:"m_geo_8", domain:"math", topic:"geometria", dif:3,
    stem:"Un círculo tiene un radio de 7 cm. Use π ≈ 22/7.",
    q:"¿Cuál es su área?",
    opts:["44 cm²","154 cm²","154 cm","308 cm²"],
    ans:1, exp:"Área = π·r² = (22/7)·7² = (22/7)·49 = 22·7 = 154 cm²." },

  /* -- Sucesiones -- */
  { id:"m_suc_6", domain:"math", topic:"sucesiones", dif:2,
    stem:"Observe la sucesión: 3, 6, 12, 24, …",
    q:"¿Cuál es el siguiente término?",
    opts:["36","48","30","40"],
    ans:1, exp:"Cada término se multiplica por 2: 24 × 2 = 48." },
  { id:"m_suc_7", domain:"math", topic:"sucesiones", dif:2,
    stem:"Observe la sucesión: 5, 9, 13, 17, …",
    q:"¿Cuál es el décimo término?",
    opts:["37","41","45","40"],
    ans:1, exp:"Es aritmética con d = 4. a₁₀ = 5 + (10−1)·4 = 5 + 36 = 41." },
  { id:"m_suc_8", domain:"math", topic:"sucesiones", dif:3,
    stem:"Observe la sucesión: 1, 2, 4, 7, 11, 16, …",
    q:"¿Cuál es el siguiente número?",
    opts:["20","21","22","23"],
    ans:2, exp:"Las diferencias crecen: +1, +2, +3, +4, +5. El siguiente suma +6: 16 + 6 = 22." },
  { id:"m_suc_9", domain:"math", topic:"sucesiones", dif:2,
    stem:"Observe la sucesión: 2, 5, 10, 17, 26, …",
    q:"¿Cuál es el siguiente número?",
    opts:["35","36","37","50"],
    ans:2, exp:"Las diferencias son 3, 5, 7, 9; la siguiente es 11: 26 + 11 = 37. (También n²+1: 6²+1 = 37.)" },

  /* -- Datos y probabilidad -- */
  { id:"m_dat_5", domain:"math", topic:"datos_probabilidad", dif:2,
    stem:"Las notas de un estudiante fueron 7, 8, 6, 9 y 10.",
    q:"¿Cuál es su promedio?",
    opts:["7","8","8,5","40"],
    ans:1, exp:"Promedio = (7+8+6+9+10) ÷ 5 = 40 ÷ 5 = 8." },
  { id:"m_dat_6", domain:"math", topic:"datos_probabilidad", dif:2,
    stem:"En una urna hay 3 bolas verdes, 5 rojas y 2 azules. Se saca una al azar.",
    q:"¿Cuál es la probabilidad de que sea azul?",
    opts:["1/5","1/2","2/5","1/10"],
    ans:0, exp:"Hay 10 bolas en total y 2 azules: 2/10 = 1/5." },
  { id:"m_dat_7", domain:"math", topic:"datos_probabilidad", dif:1,
    stem:"Se lanza un dado común de 6 caras.",
    q:"¿Cuál es la probabilidad de obtener un número mayor que 4?",
    opts:["1/3","1/2","2/3","1/6"],
    ans:0, exp:"Mayores que 4: el 5 y el 6 (2 casos). Probabilidad = 2/6 = 1/3." },
  { id:"m_dat_8", domain:"math", topic:"datos_probabilidad", dif:3,
    stem:"El promedio de 4 números es 15. Tres de ellos son 12, 18 y 10.",
    q:"¿Cuál es el cuarto número?",
    opts:["15","18","20","25"],
    ans:2, exp:"La suma total es 4·15 = 60. Los tres dados suman 40, así que el cuarto es 60 − 40 = 20." },

  /* -- Notación algebraica -- */
  { id:"m_not_4", domain:"math", topic:"algebra_notacion", dif:2,
    stem:"Considere la frase: 'la mitad de un número, aumentada en 7'.",
    q:"¿Cuál expresión la representa?",
    opts:["x/2 + 7","2x + 7","(x + 7)/2","7 − x/2"],
    ans:0, exp:"La mitad del número es x/2; aumentada en 7 es x/2 + 7." },
  { id:"m_not_5", domain:"math", topic:"algebra_notacion", dif:2,
    stem:"Ana tiene n años. Su mamá tiene 4 años menos que el triple de la edad de Ana.",
    q:"¿Qué expresión representa la edad de la mamá?",
    opts:["3n − 4","3(n − 4)","4 − 3n","n/3 − 4"],
    ans:0, exp:"El triple de Ana es 3n; '4 menos que eso' es 3n − 4." },
  { id:"m_not_6", domain:"math", topic:"algebra_notacion", dif:2,
    stem:"Considere la frase: 'el cuadrado de la suma de un número y 3'.",
    q:"¿Cuál expresión la representa?",
    opts:["x² + 3","(x + 3)²","x² + 9","2(x + 3)"],
    ans:1, exp:"Primero la suma (x + 3) y luego su cuadrado: (x + 3)². Es distinto de x² + 9." },

  /* -- Relaciones algebraicas y paridad -- */
  { id:"m_alr_4", domain:"math", topic:"algebra_relaciones", dif:2,
    stem:"Se sabe que 2x − 5 = 11.",
    q:"¿Cuál es el valor de x?",
    opts:["3","8","6","16"],
    ans:1, exp:"2x = 11 + 5 = 16, entonces x = 8." },
  { id:"m_alr_5", domain:"math", topic:"algebra_relaciones", dif:3,
    stem:"Sea n un número entero cualquiera.",
    q:"¿Cuál de las siguientes expresiones representa siempre un número impar?",
    opts:["2n","n + 2","2n + 1","n²"],
    ans:2, exp:"2n es par para todo entero, así que 2n + 1 es siempre impar. Las otras dependen de n." },
  { id:"m_alr_6", domain:"math", topic:"algebra_relaciones", dif:2,
    stem:"Se suman dos números impares cualesquiera.",
    q:"¿Cómo es siempre el resultado?",
    opts:["Impar","Par","Primo","Igual a cero"],
    ans:1, exp:"Impar + impar = par (por ejemplo 3 + 5 = 8). Siempre da un número par." },

  /* -- Unidades de medida -- */
  { id:"m_uni_5", domain:"math", topic:"unidades_medida", dif:2,
    stem:"Considere un tiempo de 2,5 horas.",
    q:"¿A cuántos minutos equivale?",
    opts:["120 min","150 min","250 min","145 min"],
    ans:1, exp:"1 h = 60 min, así que 2,5 h = 2,5 × 60 = 150 min." },
  { id:"m_uni_6", domain:"math", topic:"unidades_medida", dif:3,
    stem:"Un tren viaja a una velocidad constante de 120 km/h.",
    q:"¿Qué distancia recorre en 15 minutos?",
    opts:["30 km","60 km","8 km","20 km"],
    ans:0, exp:"15 min = 1/4 de hora. Distancia = 120 × 1/4 = 30 km." },
  { id:"m_uni_7", domain:"math", topic:"unidades_medida", dif:2,
    stem:"Una jarra contiene 3/4 de litro de jugo.",
    q:"¿A cuántos mililitros equivale?",
    opts:["75 ml","750 ml","7 500 ml","340 ml"],
    ans:1, exp:"1 litro = 1 000 ml, entonces 3/4 de litro = 750 ml." },

  /* -- Razón y proporción -- */
  { id:"m_raz_5", domain:"math", topic:"razon_proporcion", dif:2,
    stem:"Cuatro obreros pintan una casa en 9 días, trabajando al mismo ritmo.",
    q:"¿Cuántos días tardarían 6 obreros en pintar la misma casa?",
    opts:["6 días","13 días","4 días","12 días"],
    ans:0, exp:"Proporción inversa: 4·9 = 36 obrero-días. Con 6 obreros: 36 ÷ 6 = 6 días." },
  { id:"m_raz_6", domain:"math", topic:"razon_proporcion", dif:2,
    stem:"Una receta para 4 personas usa 6 huevos.",
    q:"¿Cuántos huevos se necesitan para 10 personas, manteniendo la proporción?",
    opts:["12","15","18","20"],
    ans:1, exp:"6 huevos ÷ 4 personas = 1,5 huevos por persona. Para 10: 1,5 × 10 = 15 huevos." },
  { id:"m_raz_7", domain:"math", topic:"razon_proporcion", dif:3,
    stem:"Un auto recorre 240 km con 16 litros de gasolina.",
    q:"¿Cuántos litros necesita para recorrer 90 km al mismo rendimiento?",
    opts:["5 L","6 L","8 L","7,5 L"],
    ans:1, exp:"Rendimiento: 240 ÷ 16 = 15 km por litro. Para 90 km: 90 ÷ 15 = 6 litros." },

  /* ===================== LOTE 2 — 50 preguntas nuevas ===================== */

  /* -- Verbal: finalidad -- */
  { id:"v_fin_8", domain:"verbal", topic:"finalidad", dif:2,
    stem:"Una empresa ofrece capacitaciones gratuitas a sus empleados para mejorar su desempeño.",
    q:"¿Cuál es la finalidad de las capacitaciones?",
    opts:["Gastar el presupuesto","Mejorar el desempeño de los empleados","Contratar más personal","Reducir los salarios"],
    ans:1, exp:"Se ofrecen 'para mejorar su desempeño': esa es la finalidad." },
  { id:"v_fin_9", domain:"verbal", topic:"finalidad", dif:1,
    stem:"El municipio pintó líneas y colocó señales cerca de la escuela para proteger a los peatones.",
    q:"¿Cuál es la finalidad de esas medidas?",
    opts:["Embellecer la calle","Proteger a los peatones","Cobrar multas","Cerrar la escuela"],
    ans:1, exp:"El propósito declarado es proteger a los peatones." },

  /* -- Verbal: comportamiento -- */
  { id:"v_com_8", domain:"verbal", topic:"comportamiento", dif:2,
    stem:"Ante un examen sorpresa, varios estudiantes se ponen nerviosos y se quedan en blanco.",
    q:"¿Cómo se comportan esos estudiantes?",
    opts:["Se concentran mejor","Se bloquean por los nervios","Lo celebran","Se duermen"],
    ans:1, exp:"La conducta descrita es bloquearse por los nervios." },
  { id:"v_com_9", domain:"verbal", topic:"comportamiento", dif:2,
    stem:"Ante una opinión distinta, Marcos escucha, pregunta y luego responde con respeto.",
    q:"¿Cómo se comporta Marcos?",
    opts:["Se ofende","Dialoga con respeto","Se va molesto","Ignora al otro"],
    ans:1, exp:"Escuchar, preguntar y responder con respeto es dialogar." },

  /* -- Verbal: causa y consecuencia -- */
  { id:"v_cau_10", domain:"verbal", topic:"causa_consecuencia", dif:2,
    stem:"Debido a las fuertes lluvias, se canceló el partido de fútbol.",
    q:"¿Cuál fue la causa de la cancelación?",
    opts:["El cansancio de los jugadores","Las fuertes lluvias","La falta de público","Un error del árbitro"],
    ans:1, exp:"'Debido a' introduce la causa: las fuertes lluvias." },
  { id:"v_cau_11", domain:"verbal", topic:"causa_consecuencia", dif:2,
    stem:"Estudió toda la noche; por eso, al día siguiente estaba agotado.",
    q:"¿Cuál es la consecuencia de estudiar toda la noche?",
    opts:["Estaba descansado","Estaba agotado","No fue a clase","Aprobó sin estudiar"],
    ans:1, exp:"'Por eso' marca la consecuencia: el agotamiento." },
  { id:"v_cau_12", domain:"verbal", topic:"causa_consecuencia", dif:3,
    stem:"El uso constante de protector solar reduce el riesgo de quemaduras en la piel.",
    q:"¿Qué relación de causa y consecuencia plantea el texto?",
    opts:["El protector causa quemaduras","Usar protector reduce el riesgo de quemaduras","El sol no daña la piel","Las quemaduras son inevitables"],
    ans:1, exp:"La causa (usar protector) tiene como consecuencia menos quemaduras." },

  /* -- Verbal: simple y complejo -- */
  { id:"v_sim_8", domain:"verbal", topic:"simple_complejo", dif:2,
    stem:"Armar un sándwich lleva dos o tres pasos; preparar un pastel de bodas implica recetas, tiempos de horneado y decoración detallada.",
    q:"¿Cómo es el pastel frente al sándwich?",
    opts:["Más simple","Más complejo","Más barato","Más rápido"],
    ans:1, exp:"El pastel reúne muchos pasos y partes: es más complejo." },
  { id:"v_sim_9", domain:"verbal", topic:"simple_complejo", dif:1,
    stem:"Una nota corta de dos líneas se escribe en un momento.",
    q:"¿Cómo es esa tarea?",
    opts:["Compleja","Simple","Costosa","Lenta"],
    ans:1, exp:"De pocos pasos y rápida: es simple." },

  /* -- Verbal: conceptualización -- */
  { id:"v_con_10", domain:"verbal", topic:"conceptualizacion", dif:2,
    stem:"Repartió su almuerzo con un compañero que había olvidado el suyo, sin que se lo pidieran.",
    q:"¿Qué palabra describe su actitud?",
    opts:["Solidaridad","Envidia","Pereza","Orgullo"],
    ans:0, exp:"Ayudar de forma espontánea se conceptualiza como solidaridad." },
  { id:"v_con_11", domain:"verbal", topic:"conceptualizacion", dif:2,
    stem:"Llegó puntual a cada cita durante todo el año, sin faltar ni una vez.",
    q:"¿Qué palabra resume su conducta?",
    opts:["Puntualidad","Distracción","Pereza","Desorden"],
    ans:0, exp:"Cumplir siempre con la hora acordada es puntualidad." },

  /* -- Verbal: orden y desorden -- */
  { id:"v_ord_8", domain:"verbal", topic:"orden_desorden", dif:2,
    stem:"Las herramientas pasaron de estar tiradas por el piso a colgar ordenadas por tamaño en la pared.",
    q:"¿Qué cambio ocurrió?",
    opts:["Del orden al desorden","Del desorden al orden","De grande a pequeño","De nuevo a viejo"],
    ans:1, exp:"De tiradas (desorden) a colgadas por criterio (orden)." },
  { id:"v_ord_9", domain:"verbal", topic:"orden_desorden", dif:1,
    stem:"Los archivos del escritorio están clasificados en carpetas con nombre.",
    q:"¿Cómo está el escritorio?",
    opts:["Ordenado","Desordenado","Vacío","Roto"],
    ans:0, exp:"Clasificados por criterio: está ordenado." },

  /* -- Verbal: orden temporal -- */
  { id:"v_tmp_8", domain:"verbal", topic:"orden_temporal", dif:2,
    stem:"Para hacer café: se hierve el agua, se agrega el café, se cuela y se sirve.",
    q:"¿Qué se hace justo antes de servir?",
    opts:["Hervir el agua","Colar","Agregar el café","Lavar la taza"],
    ans:1, exp:"La secuencia es hervir → agregar → colar → servir. Antes de servir se cuela." },
  { id:"v_tmp_9", domain:"verbal", topic:"orden_temporal", dif:2,
    stem:"El atleta calienta, corre la carrera y luego estira para relajar los músculos.",
    q:"¿Qué hace después de correr?",
    opts:["Calentar","Estirar","Inscribirse","Dormir"],
    ans:1, exp:"Después de correr, estira." },

  /* -- Verbal: esencia -- */
  { id:"v_ese_8", domain:"verbal", topic:"esencia", dif:3,
    stem:"Lo propio de una brújula es señalar el norte.",
    q:"Por la misma lógica, ¿qué es lo propio de un termómetro?",
    opts:["Señalar el norte","Medir la temperatura","Medir el peso","Marcar la hora"],
    ans:1, exp:"Si la brújula sirve para orientarse, el termómetro sirve para medir la temperatura." },
  { id:"v_ese_9", domain:"verbal", topic:"esencia", dif:2,
    stem:"Una característica esencial de un puente es unir dos puntos separados por un obstáculo.",
    q:"Según el texto, ¿qué es lo propio de un puente?",
    opts:["Su color","Unir dos puntos separados","Su antigüedad","Su material"],
    ans:1, exp:"Lo característico de un puente es su función: unir dos puntos." },

  /* -- Verbal: perspectiva -- */
  { id:"v_per_9", domain:"verbal", topic:"perspectiva", dif:3,
    stem:"El mismo silencio que relaja a quien busca paz incomoda a quien teme a la soledad.",
    q:"¿Qué muestra el texto?",
    opts:["El silencio es siempre malo","Un mismo hecho se vive distinto según la persona","Nadie disfruta el silencio","El silencio no existe"],
    ans:1, exp:"El silencio se valora distinto según quién lo viva: es cuestión de perspectiva." },
  { id:"v_per_10", domain:"verbal", topic:"perspectiva", dif:2,
    stem:"Para el turista la nieve es una novedad encantadora; para el habitante del lugar, una molestia diaria.",
    q:"¿Qué idea expresa el texto?",
    opts:["La nieve es peligrosa","La misma nieve se valora distinto según quién la viva","La nieve no cae nunca","El turista exagera"],
    ans:1, exp:"Un mismo hecho (la nieve) se percibe distinto según la persona." },

  /* -- Verbal: idea implícita -- */
  { id:"v_imp_12", domain:"verbal", topic:"idea_implicita", dif:2,
    stem:"Cada vez que riega sus plantas con esa agua, las hojas se ponen amarillas.",
    q:"¿Cuál es una idea implícita?",
    opts:["Las plantas no necesitan agua","Algo en esa agua les hace daño","El sol las quema","Las plantas están sanas"],
    ans:1, exp:"Si se amarillan al regarlas con esa agua, se infiere que algo en el agua les hace daño." },
  { id:"v_imp_13", domain:"verbal", topic:"idea_implicita", dif:1,
    stem:"No quedaban entradas y la fila daba vuelta a la cuadra.",
    q:"¿Qué idea está implícita?",
    opts:["A nadie le interesaba","El evento era muy popular","Era gratis","Estaba cancelado"],
    ans:1, exp:"Entradas agotadas y fila enorme implican que el evento era muy popular." },
  { id:"v_imp_14", domain:"verbal", topic:"idea_implicita", dif:2,
    stem:"Habla tres idiomas y ha vivido en varios países.",
    q:"¿Cuál es una idea implícita?",
    opts:["Nunca salió de su ciudad","Ha tenido experiencia internacional","No sabe leer","Odia viajar"],
    ans:1, exp:"Hablar varios idiomas y vivir en varios países implica experiencia internacional." },

  /* -- Verbal: idea principal -- */
  { id:"v_pri_10", domain:"verbal", topic:"idea_principal", dif:2,
    stem:"El agua potable es escasa: hay que tratarla, distribuirla con cuidado y no desperdiciarla.",
    q:"¿Cuál es la idea principal?",
    opts:["El cuidado del agua potable","El color del agua","El precio del agua","La lluvia"],
    ans:0, exp:"Todo el texto gira en torno a cuidar el agua potable." },
  { id:"v_pri_11", domain:"verbal", topic:"idea_principal", dif:2,
    stem:"El ejercicio, una dieta balanceada y el buen descanso forman la base de una vida sana.",
    q:"¿Cuál es la idea principal?",
    opts:["Los pilares de una vida sana","Los tipos de ejercicio","Las dietas de moda","Las horas de sueño"],
    ans:0, exp:"Los tres elementos apuntan al tema: los pilares de una vida sana." },
  { id:"v_pri_12", domain:"verbal", topic:"idea_principal", dif:3,
    stem:"El volcán Arenal atrae turistas, genera empleo en la zona y es un símbolo natural de Costa Rica.",
    q:"¿Cuál es el tema central?",
    opts:["La importancia del volcán Arenal","La altura del volcán","El clima de la zona","Los hoteles del país"],
    ans:0, exp:"Los tres rasgos apuntan a la importancia del volcán Arenal." },

  /* -- Verbal: paráfrasis -- */
  { id:"v_par_9", domain:"verbal", topic:"parafrasis", dif:2,
    stem:"A palabras necias, oídos sordos.",
    q:"¿Cuál opción dice lo mismo con otras palabras?",
    opts:["Hay que responder a todo insulto","Conviene no prestar atención a los comentarios necios","Las palabras siempre lastiman","Hay que hablar mucho"],
    ans:1, exp:"El refrán aconseja ignorar los comentarios tontos." },
  { id:"v_par_10", domain:"verbal", topic:"parafrasis", dif:2,
    stem:"El que persevera, alcanza.",
    q:"¿Cuál opción conserva el sentido?",
    opts:["Solo importa la suerte","Quien insiste con constancia logra su meta","Rendirse es lo mejor","Nada se consigue"],
    ans:1, exp:"Perseverar y alcanzar = insistir con constancia para lograr la meta." },
  { id:"v_par_11", domain:"verbal", topic:"parafrasis", dif:3,
    stem:"Roma no se construyó en un día.",
    q:"¿Cuál opción expresa la misma idea?",
    opts:["Todo se hace al instante","Las cosas grandes toman tiempo","Roma no existe","Construir es fácil"],
    ans:1, exp:"El refrán dice que los logros grandes requieren tiempo." },

  /* -- Verbal: proposiciones -- */
  { id:"v_pro_9", domain:"verbal", topic:"proposiciones", dif:3,
    stem:"Todos los que aprobaron entregaron la tarea. Analice las proposiciones:\nI. Quien no entregó la tarea no aprobó.\nII. Hay quienes aprobaron sin entregar la tarea.\nIII. Entregar la tarea fue necesario para aprobar.",
    q:"¿Cuáles proposiciones se deducen del texto?",
    opts:["Solo la II","La I y la III","Solo la I","Las tres"],
    ans:1, exp:"'Todos los aprobados entregaron' equivale a que entregar era necesario (III) y a que quien no entregó no aprobó (I). II lo contradice." },
  { id:"v_pro_10", domain:"verbal", topic:"proposiciones", dif:2,
    stem:"Cuando hay sol, la ropa se seca. Analice las proposiciones:\nI. El sol seca la ropa.\nII. La ropa se seca siempre, aun sin sol.\nIII. El sol moja la ropa.",
    q:"¿Cuál proposición se deduce del texto?",
    opts:["Solo la I","Solo la II","La II y la III","Solo la III"],
    ans:0, exp:"El texto dice que el sol seca la ropa: I. II y III no se siguen." },

  /* -- Mate: aritmética -- */
  { id:"m_ari_11", domain:"math", topic:"aritmetica", dif:1,
    stem:"Considere la operación: 7 × 8 − 6 × 5.",
    q:"¿Cuál es el resultado?",
    opts:["26","250","20","16"],
    ans:0, exp:"Primero los productos: 7×8=56 y 6×5=30. Luego 56 − 30 = 26." },
  { id:"m_ari_12", domain:"math", topic:"aritmetica", dif:2,
    stem:"Un café cuesta ₡1 200.",
    q:"¿Cuánto cuestan 7 cafés?",
    opts:["₡7 200","₡8 400","₡9 600","₡8 000"],
    ans:1, exp:"1 200 × 7 = 8 400." },
  { id:"m_ari_13", domain:"math", topic:"aritmetica", dif:2,
    stem:"Un tanque está a 3/4 de su capacidad y se usa 1/2 del total.",
    q:"¿Qué fracción del tanque queda?",
    opts:["1/4","1/2","1/3","3/8"],
    ans:0, exp:"3/4 − 1/2 = 3/4 − 2/4 = 1/4." },

  /* -- Mate: MCM y MCD -- */
  { id:"m_mcm_8", domain:"math", topic:"mcm_mcd", dif:2,
    stem:"Dos campanas suenan: una cada 6 minutos y otra cada 9 minutos. Ahora sonaron juntas.",
    q:"¿En cuántos minutos vuelven a sonar juntas?",
    opts:["12","18","54","15"],
    ans:1, exp:"Coinciden en el MCM(6, 9). 6 = 2·3 y 9 = 3², así que MCM = 2·3² = 18." },

  /* -- Mate: relaciones de orden -- */
  { id:"m_rel_8", domain:"math", topic:"relaciones_orden", dif:2,
    stem:"Considere los valores 0,5 ; 1/3 ; 0,25.",
    q:"¿Cuál es el mayor?",
    opts:["0,5","1/3","0,25","Son iguales"],
    ans:0, exp:"En decimales: 0,50 ; 0,33 ; 0,25. El mayor es 0,5." },
  { id:"m_rel_9", domain:"math", topic:"relaciones_orden", dif:2,
    stem:"Se sabe que a > 0 y que b < 0.",
    q:"¿Cuál afirmación es siempre verdadera?",
    opts:["b es mayor que a","a es mayor que b","a es igual a b","b es positivo"],
    ans:1, exp:"Un positivo siempre es mayor que un negativo: a > b." },

  /* -- Mate: conteo -- */
  { id:"m_cnt_8", domain:"math", topic:"conteo", dif:2,
    stem:"Hay 4 caminos de A a B y 3 caminos de B a C.",
    q:"¿De cuántas formas se puede ir de A a C pasando por B?",
    opts:["7","12","9","16"],
    ans:1, exp:"Principio multiplicativo: 4 × 3 = 12 rutas." },
  { id:"m_cnt_9", domain:"math", topic:"conteo", dif:3,
    stem:"En una caja, a oscuras, hay 4 guantes izquierdos y 4 derechos sueltos.",
    q:"¿Cuántos guantes hay que sacar como mínimo para asegurar una pareja útil (uno izquierdo y uno derecho)?",
    opts:["2","5","4","8"],
    ans:1, exp:"En el peor caso salen los 4 de una misma mano; el siguiente es de la otra. 4 + 1 = 5." },

  /* -- Mate: permutaciones -- */
  { id:"m_per_7", domain:"math", topic:"permutaciones", dif:3,
    stem:"En un concurso con 5 participantes se reparten el 1.°, 2.° y 3.° lugar.",
    q:"¿De cuántas formas distintas pueden quedar esos tres puestos?",
    opts:["15","60","125","10"],
    ans:1, exp:"Se eligen y ordenan 3 de 5: 5 × 4 × 3 = 60." },

  /* -- Mate: geometría -- */
  { id:"m_geo_9", domain:"math", topic:"geometria", dif:2,
    stem:"Un rectángulo mide 12 cm de largo y 7 cm de ancho.",
    q:"¿Cuál es su perímetro?",
    opts:["38 cm","84 cm","19 cm","40 cm"],
    ans:0, exp:"Perímetro = 2·(12 + 7) = 2·19 = 38 cm." },
  { id:"m_geo_10", domain:"math", topic:"geometria", dif:2,
    stem:"Un cuadrado tiene lados de 11 cm.",
    q:"¿Cuál es su área?",
    opts:["44 cm²","121 cm²","22 cm²","132 cm²"],
    ans:1, exp:"Área del cuadrado = lado² = 11² = 121 cm²." },

  /* -- Mate: sucesiones -- */
  { id:"m_suc_10", domain:"math", topic:"sucesiones", dif:2,
    stem:"Observe la sucesión: 100, 50, 25, … (cada término es la mitad del anterior).",
    q:"¿Cuál es el siguiente término?",
    opts:["10","12,5","20","15"],
    ans:1, exp:"Cada término se divide entre 2: 25 ÷ 2 = 12,5." },
  { id:"m_suc_11", domain:"math", topic:"sucesiones", dif:2,
    stem:"Observe la sucesión: 1, 4, 9, 16, 25, …",
    q:"¿Cuál es el siguiente número?",
    opts:["30","36","49","32"],
    ans:1, exp:"Son los cuadrados (1², 2², 3²…). El siguiente es 6² = 36." },

  /* -- Mate: datos y probabilidad -- */
  { id:"m_dat_9", domain:"math", topic:"datos_probabilidad", dif:2,
    stem:"En una bolsa hay 8 caramelos: 3 de menta y 5 de fresa. Se saca uno al azar.",
    q:"¿Cuál es la probabilidad de que sea de menta?",
    opts:["3/8","5/8","3/5","1/3"],
    ans:0, exp:"Favorables 3 sobre 8 totales: 3/8." },
  { id:"m_dat_10", domain:"math", topic:"datos_probabilidad", dif:2,
    stem:"Las edades de tres hermanos son 8, 11 y 14 años.",
    q:"¿Cuál es el promedio de sus edades?",
    opts:["10","11","12","33"],
    ans:1, exp:"(8 + 11 + 14) ÷ 3 = 33 ÷ 3 = 11." },

  /* -- Mate: notación algebraica -- */
  { id:"m_not_7", domain:"math", topic:"algebra_notacion", dif:2,
    stem:"Considere la frase: 'un número disminuido en 9, todo multiplicado por 2'.",
    q:"¿Cuál expresión la representa?",
    opts:["2(x − 9)","2x − 9","x − 18","2x + 9"],
    ans:0, exp:"Primero la resta (x − 9) y luego se multiplica todo por 2: 2(x − 9)." },

  /* -- Mate: relaciones algebraicas -- */
  { id:"m_alr_7", domain:"math", topic:"algebra_relaciones", dif:2,
    stem:"Se sabe que 3x = 21.",
    q:"¿Cuánto vale x + 4?",
    opts:["7","11","25","18"],
    ans:1, exp:"x = 21 ÷ 3 = 7, entonces x + 4 = 11." },

  /* -- Mate: unidades de medida -- */
  { id:"m_uni_8", domain:"math", topic:"unidades_medida", dif:2,
    stem:"Un recipiente tiene 2 litros de agua y se sirve en vasos de 250 ml.",
    q:"¿Cuántos vasos se llenan?",
    opts:["4","8","5","10"],
    ans:1, exp:"2 L = 2 000 ml. 2 000 ÷ 250 = 8 vasos." },

  /* -- Mate: razón y proporción -- */
  { id:"m_raz_8", domain:"math", topic:"razon_proporcion", dif:2,
    stem:"Tres lápices cuestan ₡900.",
    q:"¿Cuánto cuestan 5 lápices al mismo precio?",
    opts:["₡1 200","₡1 500","₡1 800","₡1 350"],
    ans:1, exp:"Cada lápiz: 900 ÷ 3 = 300. Cinco lápices: 300 × 5 = 1 500." },
  { id:"m_raz_9", domain:"math", topic:"razon_proporcion", dif:3,
    stem:"Un grifo llena un tanque en 8 horas.",
    q:"¿Cuánto tardan 2 grifos iguales llenándolo juntos?",
    opts:["4 horas","16 horas","6 horas","10 horas"],
    ans:0, exp:"Proporción inversa: con el doble de grifos, la mitad del tiempo. 8 ÷ 2 = 4 horas." }
];

/* Sumamos las preguntas extra al banco principal y reconstruimos el índice */
window.PAA_QUESTIONS = (window.PAA_QUESTIONS || []).concat(window.PAA_QUESTIONS_EXTRA);
window.PAA_QUESTIONS_BY_TOPIC = window.PAA_QUESTIONS.reduce(function (m, q) {
  (m[q.topic] = m[q.topic] || []).push(q);
  return m;
}, {});
