import json

with open('e:/Gemini Projects/PAASAU UCR UNA/paasau/temp_chunks/chunk_11.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

updates = {
    'm_alr_4': {
        'stem': 'Considere la ecuación lineal $3(x - 2) = 18$, donde $x$ representa una constante en un sistema matemático.',
        'q': 'De acuerdo con dicha ecuación, ¿cuál es el valor numérico de la expresión $x + 5$?',
        'opts': ['13', '8', '11', '19'],
        'exp': 'Para resolver este problema, primero debemos despejar el valor de $x$ en la ecuación inicial.\n\n*   Dividimos ambos lados de la ecuación entre 3: $x - 2 = 6$.\n*   Sumamos 2 a ambos lados: $x = 8$.\n\nAhora, evaluamos la expresión solicitada sustituyendo el valor de $x$:\n\n*   $x + 5 = 8 + 5 = 13$.\n\n**Tip Élite:** Lee siempre qué te piden al final. Un error común es calcular el valor de la incógnita ($x=8$) y seleccionarlo impulsivamente entre las opciones sin responder a la pregunta real.'
    },
    'm_alr_5': {
        'stem': 'Sea $n$ un número entero que pertenece al conjunto de los números enteros ($\\mathbb{Z}$).',
        'q': '¿Cuál de las siguientes expresiones algebraicas garantiza como resultado un número impar para cualquier valor de $n$?',
        'opts': ['$2n$', '$n + 2$', '$2n + 1$', '$n^2 + n$'],
        'exp': 'Analicemos la paridad de cada expresión algebraica dada para un entero $n$ cualquiera:\n\n*   **$2n$:** Al estar multiplicado por 2, siempre resultará en un número par.\n*   **$n + 2$:** Su paridad depende exclusivamente de $n$; si $n$ es par, será par, y si $n$ es impar, será impar.\n*   **$n^2 + n$:** Factorizado como $n(n+1)$, representa el producto de dos enteros consecutivos, lo cual siempre es un número par.\n*   **$2n + 1$:** Dado que $2n$ es indefectiblemente par, al sumarle 1 obtenemos obligatoriamente un número impar.\n\n**Tip Élite:** Cuando te enfrentes a expresiones algebraicas de paridad, puedes sustituir mentalmente $n$ por un número par (ej. 2) y uno impar (ej. 1) para descartar opciones rápidamente.'
    },
    'm_alr_6': {
        'stem': 'Considere dos números enteros, $a$ y $b$, cuyo producto algebraico arroja como resultado un número par.',
        'q': '¿Cuál de las siguientes afirmaciones se deduce con absoluta certeza respecto a $a$ y $b$?',
        'opts': ['Ambos factores deben ser necesariamente impares', 'Al menos uno de los factores debe ser par', 'Ambos factores deben ser ineludiblemente pares', 'La suma de ambos factores es un número impar'],
        'exp': 'Para deducir la certeza, debemos recordar las reglas de multiplicación de enteros según su paridad:\n\n*   Impar $\\times$ Impar = Impar.\n*   Par $\\times$ Impar = Par.\n*   Par $\\times$ Par = Par.\n\nComo el resultado es par, basta con que uno de los dos factores aporte el factor 2 en su descomposición prima. Por lo tanto, no es necesario que ambos sean pares, pero es estrictamente obligatorio que **al menos uno** lo sea.\n\n**Tip Élite:** No confundas \"puede ser\" con \"debe ser\". Aunque ambos factores pueden ser pares, la única afirmación categóricamente cierta en todos los casos es que al menos uno de ellos lo es.'
    },
    'm_uni_5': {
        'stem': 'La proyección de un largometraje cinematográfico tiene una duración exacta de 2 horas y 35 minutos sin interrupciones.',
        'q': '¿A cuántos minutos equivale la duración total de la cinta?',
        'opts': ['155', '235', '205', '255'],
        'exp': 'Para realizar la conversión de tiempo adecuadamente, debemos estandarizar las unidades a la magnitud requerida.\n\n*   Sabemos que $1 \\text{ hora} = 60 \\text{ minutos}$.\n*   Por lo tanto, calculamos la equivalencia de las horas: $2 \\text{ horas} \\times 60 = 120 \\text{ minutos}$.\n*   Sumamos los minutos restantes de la fracción final: $120 + 35 = 155 \\text{ minutos}$.\n\n**Tip Élite:** Mucho cuidado con el distractor visual $235$, que proviene de simplemente juntar el '2' y el '35'. El tiempo se basa en un sistema sexagesimal, no decimal.'
    },
    'm_uni_6': {
        'stem': 'Un tren de alta velocidad se desplaza en línea recta manteniendo una velocidad constante de $120\\text{ km/h}$.',
        'q': '¿Qué distancia, expresada en kilómetros, logrará recorrer en un lapso de 15 minutos?',
        'opts': ['30', '1800', '18', '20'],
        'exp': 'Para calcular la distancia, necesitamos que el tiempo y la velocidad compartan la misma unidad de medida temporal.\n\n*   Convertimos los minutos a horas mediante una fracción: $15 \\text{ minutos} = \\frac{15}{60} \\text{ horas} = \\frac{1}{4} \\text{ de hora}$.\n*   Aplicamos la fórmula básica del movimiento uniforme ($d = v \\times t$).\n*   Sustituimos los valores y resolvemos la fracción: $d = 120 \\times \\frac{1}{4} = 30 \\text{ kilómetros}$.\n\n**Tip Élite:** Trabajar con fracciones comunes como $\\frac{1}{4}$ de hora en lugar de decimales o reglas de tres largas agiliza enormemente el cálculo mental en el examen.'
    },
    'm_uni_7': {
        'stem': 'En un evento, un dispensador contiene inicialmente $1,5\\text{ litros}$ de jugo. Se sirven de manera exacta 3 vasos con una capacidad de $250\\text{ ml}$ cada uno.',
        'q': '¿Cuál es el volumen de jugo, medido en mililitros, que permanece en el dispensador?',
        'opts': ['750', '1250', '500', '250'],
        'exp': 'Para resolver este problema, la clave es homogenizar las unidades de volumen antes de operar.\n\n*   Primero, convertimos el volumen inicial a mililitros: $1,5\\text{ L} \\times 1000\\text{ ml/L} = 1500\\text{ ml}$.\n*   Luego, calculamos el volumen total extraído: $3\\text{ vasos} \\times 250\\text{ ml} = 750\\text{ ml}$.\n*   Finalmente, restamos el líquido servido del inicial: $1500\\text{ ml} - 750\\text{ ml} = 750\\text{ ml}$.\n\n**Tip Élite:** Siempre asegúrate de realizar las operaciones matemáticas (sumas y restas) utilizando la unidad de medida que te exigen en la pregunta (en este caso, mililitros).'
    },
    'm_raz_5': {
        'stem': 'Un equipo conformado por 4 obreros requiere exactamente 9 días para pintar la fachada de un edificio habitacional, laborando todos al mismo ritmo.',
        'q': '¿Cuántos días requeriría un equipo de 6 obreros bajo las mismas condiciones para completar idéntica tarea?',
        'opts': ['6', '13,5', '5,4', '12'],
        'exp': 'Este problema plantea una proporcionalidad inversa, ya que a mayor cantidad de obreros, menor será el tiempo necesario.\n\n*   Calculamos el esfuerzo total requerido medido en obreros-día: $4 \\text{ obreros} \\times 9 \\text{ días} = 36 \\text{ obreros-día}$.\n*   Para encontrar el nuevo tiempo, dividimos el esfuerzo total entre el nuevo número de obreros: $36 \\div 6 = 6 \\text{ días}$.\n\n**Tip Élite:** Si cometes el error de usar una regla de tres directa, obtendrás $13,5$ días (un poderoso distractor). Siempre pregúntate primero: Si aumento esta variable, ¿la otra debería subir o bajar?'
    },
    'm_raz_6': {
        'stem': 'La elaboración de una receta de repostería requiere $450\\text{ g}$ de harina refinada para obtener un rendimiento exacto de 6 porciones estándar.',
        'q': '¿Cuántos gramos de harina serán necesarios para producir 10 porciones, asumiendo una proporcionalidad directa constante?',
        'opts': ['750', '270', '900', '720'],
        'exp': 'Al tratar con recetas de cocina, nos enfrentamos a un caso típico de proporcionalidad directa (a más porciones, más insumos).\n\n*   Determinamos primero la cantidad unitaria (harina por porción): $450\\text{ g} \\div 6 = 75\\text{ g/porción}$.\n*   Luego, multiplicamos esta constante por el número deseado de porciones: $75\\text{ g} \\times 10 = 750\\text{ g}$.\n\n**Tip Élite:** Puedes resolverlo también empleando fracciones equivalentes: $\\frac{450}{6} = \\frac{x}{10}$. Simplificando $\\frac{450}{6}$ a $75$, simplemente lo multiplicas de manera directa por $10$.'
    },
    'm_raz_7': {
        'stem': 'Bajo condiciones óptimas de circulación, un automóvil consume 16 litros de combustible para recorrer una distancia de $240\\text{ km}$.',
        'q': 'Si se mantiene rigurosamente el mismo rendimiento, ¿cuántos litros de combustible demandará un trayecto de $90\\text{ km}$?',
        'opts': ['5', '6', '8', '7,5'],
        'exp': 'Este es un ejercicio de rendimiento constante, por lo que aplicamos un análisis de proporcionalidad directa.\n\n*   Calculamos el rendimiento del vehículo (kilómetros por litro): $240\\text{ km} \\div 16\\text{ L} = 15\\text{ km/L}$.\n*   Conociendo la nueva distancia objetivo, dividimos entre el rendimiento para obtener el consumo necesario: $90\\text{ km} \\div 15\\text{ km/L} = 6\\text{ L}$.\n\n**Tip Élite:** Si tienes problemas con divisiones de dos cifras en la prueba, simplifica la fracción primero: $\\frac{240}{16} = \\frac{120}{8} = \\frac{60}{4} = 15$. La simplificación progresiva es tu mejor aliada para evitar errores en el papel.'
    },
    'v_fin_8': {
        'stem': 'Una corporación asume el financiamiento de programas de actualización profesional para sus empleados dentro del horario laboral. Pese a que esto representa una merma de horas efectivas y un considerable desembolso económico, la directiva argumenta que el retorno de la inversión se refleja en una notable optimización del desempeño operativo.',
        'q': '¿Cuál es el propósito medular que persigue la corporación al implementar estos programas de actualización?',
        'opts': ['Agotar el presupuesto anual asignado para capacitación e impuestos', 'Incrementar la eficacia y desempeño integral de la plantilla operativa', 'Minimizar la cantidad de horas laborables netas del personal', 'Sustituir gradualmente a los empleados menos calificados'],
        'exp': 'Para identificar el propósito medular, debemos diferenciar firmemente entre los costos asumidos y el objetivo superior deseado.\n\n*   El texto menciona explícitamente que la optimización del desempeño operativo (trabaja mejor) es el retorno que justifica todo el esfuerzo financiero.\n*   La merma de horas y el desembolso económico son obstáculos asumidos con resignación, no finalidades en sí mismas.\n*   Las demás opciones plantean intenciones punitivas o administrativas no amparadas por la premisa.\n\n**Tip Élite:** La finalidad en comprensión lectora siempre responde a la pregunta implícita de ¿para qué se asume un sacrificio?. Busca el beneficio último declarado conscientemente por el emisor.'
    },
    'v_fin_9': {
        'stem': 'Con motivo de la temporada de evaluaciones, el consejo directivo de la biblioteca extendió el horario de servicio hasta la medianoche. El director enfatizó que la medida no pretende mermar las horas de sueño de los estudiantes, sino proveer un recinto libre de distracciones para aquellos cuyos hogares carecen de un entorno propicio para la concentración.',
        'q': '¿Cuál es el objetivo primordial que justifica la extensión del horario de servicio?',
        'opts': ['Fomentar que los estudiantes reduzcan drásticamente sus horas de descanso', 'Suministrar un espacio idóneo y silencioso para el análisis y estudio', 'Incrementar artificialmente el gasto operativo del recinto institucional', 'Establecer una competencia de servicios con otros centros de la ciudad'],
        'exp': 'El análisis de finalidad exige diferenciar pulcramente entre las posibles consecuencias colaterales y el objetivo formalmente declarado.\n\n*   El director descarta explícitamente la intención maliciosa de que duerman menos, anulando categóricamente esa opción como finalidad directiva.\n*   El texto declara literalmente que la intención medular es proveer un recinto libre de distracciones (entorno propicio) para estudiar.\n*   Opciones como el gasto operativo o la competencia mercadológica no se derivan en absoluto de las premisas presentadas.\n\n**Tip Élite:** Presta mucha atención a las aclaraciones del autor que comienzan con negaciones (no busca..., no pretende...). Suelen estar puestas ahí precisamente para adelantarse y destruir los distractores más tentadores.'
    },
    'v_com_8': {
        'stem': 'Al ser notificados de una evaluación intempestiva, una fracción significativa del alumnado experimentó taquicardia, sufrió una amnesia temporal sobre los contenidos repasados y mantuvo la mirada extraviada frente al formato en blanco.',
        'q': '¿Qué estado psicológico subyace predominantemente en la conducta descrita de estos alumnos?',
        'opts': ['Focalización extrema del pensamiento', 'Bloqueo cognitivo originado por una ansiedad aguda', 'Júbilo desmesurado ante el reto intelectual', 'Serenidad expectante y control situacional'],
        'exp': 'Debemos abstraer el comportamiento físico detallado en el texto y clasificarlo en un esquema psicológico patognomónico.\n\n*   La taquicardia (pulso acelerado) y la amnesia temporal (olvido repentino de la materia) son respuestas fisiológicas y cognitivas clásicas del estrés agudo.\n*   Mantener la mirada extraviada ante el papel en blanco confirma indudablemente un estado de parálisis motora o bloqueo cognitivo severo.\n*   Las demás opciones (focalización, júbilo o serenidad) son semánticamente incompatibles con estos síntomas negativos.\n\n**Tip Élite:** Cuando te pidan inferir un estado psicológico, asocia invariablemente los marcadores orgánicos y conductuales (taquicardia, parálisis, sudoración) con la emoción subyacente correspondiente (miedo, pánico o ansiedad).'
    },
    'v_com_9': {
        'stem': 'Al enfrentarse a posturas diametralmente opuestas a las suyas, Marcos evita el agravio: atiende íntegramente la exposición, indaga para comprender la perspectiva ajena y, posteriormente, articula su propia argumentación sin recurrir a falacias ad hominem.',
        'q': '¿Qué modelo de interacción comunicativa caracteriza la actitud de Marcos frente a la discrepancia?',
        'opts': ['Evasión sistemática del conflicto ideológico', 'Diálogo constructivo fundamentado en la tolerancia', 'Capitulación intelectual e ideológica inmediata', 'Imposición dogmática de sus propias ideas'],
        'exp': 'El texto nos exige decodificar y etiquetar conceptualmente un protocolo de comportamiento moral y conductual frente a un debate.\n\n*   Marcos no evade el tema (ya que articula su propia argumentación al final), ni claudica cobardemente (porque expone su punto con firmeza), ni se impone agresivamente (porque no usa ataques personales).\n*   Escuchar íntegramente, indagar para ampliar la comprensión y responder sin insultos son, por definición sociológica, los pilares de un diálogo constructivo y respetuoso.\n\n**Tip Élite:** Trata de elevar las acciones puntuales narradas (pregunta mucho, no ofende) hacia conceptos sociológicos o éticos más abarcadores (tolerancia epistémica, diálogo constructivo) para cazar al vuelo la respuesta correcta en ítems de clasificación actitudinal.'
    },
    'v_cau_10': {
        'stem': 'Las precipitaciones torrenciales acontecidas durante el fin de semana provocaron el anegamiento del campo de juego; en consecuencia, el encuentro deportivo fue suspendido y postergado para el mes venidero.',
        'q': '¿Cuál es la articulación lógico-causal que estructura la secuencia de eventos descrita?',
        'opts': ['La postergación del partido es la causa matriz de las precipitaciones torrenciales', 'El anegamiento pluvial opera como factor desencadenante de la suspensión', 'La suspensión del encuentro provocó el deterioro hidrológico del campo', 'Los eventos narrados transcurren de forma aislada, sin ningún nexo causal'],
        'exp': 'Para establecer de forma inequívoca la articulación lógico-causal, resulta insustituible trazar la línea cronológica de los sucesos.\n\n*   El evento inicial e independiente es netamente climático: las precipitaciones torrenciales.\n*   Este evento exógeno genera una secuela sobre la infraestructura: el anegamiento físico de la cancha.\n*   La reacción administrativa institucional ante dicho estado es la consecuencia final de la cadena: la suspensión y postergación del partido.\n*   En consecuencia, las lluvias (y su inundación consecuente) operan como el motor original que desencadena la cancelación.\n\n**Tip Élite:** Los conectores lógicos intratextuales como en consecuencia, por ende o por eso actúan como faros; la cláusula que les antecede suele ser la premisa causal, y la que les sigue revela la consumación del efecto.'
    },
    'v_cau_11': {
        'stem': 'Con el afán de dominar el temario, Marcos dedicó la noche entera al estudio continuo, privándose por completo del sueño. A la mañana siguiente, acudió a la evaluación; no obstante, experimentaba severas dificultades de concentración, requería releer reiteradamente los enunciados y presentaba un cuadro de agotamiento manifiesto.',
        'q': '¿Qué efecto directo desencadenó la privación de sueño en el desempeño general de Marcos?',
        'opts': ['Una optimización de sus capacidades analíticas por el tiempo invertido', 'Un estado de relajación cognitiva pre-evaluativa', 'Un deterioro significativo de su eficiencia mental a causa de la fatiga', 'La deserción irrevocable de la prueba ante la inseguridad de sus conocimientos'],
        'exp': 'En esta interrogante resulta crucial discernir analíticamente entre la intención volitiva del sujeto y las consecuencias pragmáticas que su accionar desencadenó.\n\n*   Aunque el anhelo originario de Marcos era dominar el temario (intención pura), los marcadores semánticos (dificultades de concentración, releer, agotamiento) dictaminan un saldo indudablemente negativo.\n*   El texto evidencia paladinamente que, lejos de potenciar su rendimiento, la vigilia prolongada fungió como una barrera cognitiva grave.\n*   Se atestigua que acudió al examen, por lo que la afirmación sobre su supuesta deserción es fácticamente improcedente.\n\n**Tip Élite:** Jamás confundas las nobles intenciones de un protagonista (estudiar más para aprobar) con los efectos materiales que la prosa atestigua expresamente (empeoramiento sustancial a raíz de la fatiga profunda).'
    },
    'v_cau_12': {
        'stem': 'La aplicación sistemática de protectores solares dermatológicos disminuye sustancialmente la incidencia de quemaduras epidérmicas ante la exposición a la radiación ultravioleta.',
        'q': '¿Cómo se relacionan lógicamente los elementos expuestos en este postulado clínico?',
        'opts': ['El uso asiduo de pantallas solares representa un factor de riesgo para la epidermis', 'La aplicación preventiva del producto actúa como causa disuasoria frente al daño cutáneo', 'La radiación ultravioleta carece comprobadamente de efectos nocivos para la piel', 'El deterioro epidérmico constituye una condición genética ineludible e inherente a los seres vivos'],
        'exp': 'Este ítem desafía a identificar correctamente la direccionalidad del vector causal en una premisa orientada hacia la profilaxis médica.\n\n*   El sujeto activo promotor de la acción (causa operante) es la aplicación sistemática de protectores solares.\n*   El fenómeno que produce o instiga esta acción preventiva es la atenuación (disminuye sustancialmente la incidencia) de un trauma potencial.\n*   Consecuentemente, el ungüento protector se erige lógicamente como una barrera profiláctica o causa preventiva eficaz.\n*   Las aseveraciones que catalogan el daño como un destino ineludible niegan absurdamente la tesis central sobre la eficacia de la prevención.\n\n**Tip Élite:** En los pasajes de raigambre científica o médica, las causas no siempre engendran fenómenos positivos o nuevos; con suma frecuencia su rol causal estriba en neutralizar, mitigar o prevenir un perjuicio inminente.'
    },
    'v_sim_8': {
        'stem': 'La elaboración de un emparedado básico consta de apenas un par de pasos sucesivos; en contraste, la confección de un pastel nupcial demanda el dominio de recetas complejas, la fiscalización de los tiempos de cocción y la ejecución de una ornamentación milimétrica.',
        'q': '¿Qué variable dicotómica fundamenta primordialmente el contraste entre ambas tareas culinarias?',
        'opts': ['La disparidad abismal en los márgenes de costo y rentabilidad', 'La asimetría notoria en el nivel de complejidad y procesos involucrados', 'La divergencia tajante en el perfil organoléptico y sabor final del producto', 'El trasfondo histórico dispar y la longevidad de las técnicas empleadas'],
        'exp': 'El meollo del análisis comparativo planteado en el texto circunvala la metodología inherente de las tareas, marginando las apreciaciones subjetivas o mercantiles.\n\n*   La prosa exhibe variables de índole puramente estructural: por una parte, un par de pasos sucesivos; por la antípoda, dominio de recetas, fiscalización cronométrica y ornamentación meticulosa.\n*   Todos estos descriptores operan como indicadores empíricos irrefutables de la escala de complejidad procedimental de la labor emprendida.\n*   Conjeturas vinculadas a la rentabilidad monetaria, la degustación del paladar o la herencia histórica son extrapolaciones infundadas que no constan en la fuente primaria.\n\n**Tip Élite:** Entrénate para adherirte dogmáticamente a los confines de la lectura. Si el narrador se afana en enumerar etapas y protocolos de supervisión, su diana argumentativa es inexorablemente la complejidad técnica, nunca las valoraciones sentimentales o hedonistas (como el sabor).'
    },
    'v_sim_9': {
        'stem': 'Llevar agua a su punto de ebullición constituye un procedimiento unívoco de un solo paso. Por el contrario, orquestar un banquete de tres tiempos para dos decenas de comensales impone la planificación logística de insumos, la cronometría de diversas cocciones y la articulación simultánea de múltiples preparaciones.',
        'q': '¿Cómo se tipifica la ejecución del banquete en contraposición a la tarea de hervir el fluido?',
        'opts': ['Exhibe un nivel de elementalidad técnica marcadamente análogo', 'Representa una empresa cualitativamente más intrincada y multivariable', 'Destaca por su celeridad excepcional y su aparente eficiencia temporal', 'Sobresale por su proverbial economía y su nulo requerimiento financiero'],
        'exp': 'El párrafo urde un marco nítido de contrastes binarios fundamentado inequívocamente en la ramificación de las variables subyacentes.\n\n*   El hervor del agua se cataloga de manera tajante como unívoco (es decir, constreñido a una solitaria variable dependiente).\n*   En las antípodas, el banquete congrega la orquestación logística, el rastreo temporal exhaustivo y la ejecución en paralelo (un entramado de múltiples variables interactuando vertiginosamente).\n*   Esta progresiva aglomeración e imbricación de procesos simultáneos encarna la definición más pura y técnica de complejidad sistémica.\n\n**Tip Élite:** Cuando un ensayo contrapone la linealidad de un suceso aislado frente a la naturaleza laberíntica de un sistema (factores en red), su objetivo perenne es radiografiar el grado de complejidad. Desestima raudamente disyuntivas sobre tarifas o cronologías si no obran cifras de respaldo en el pasaje.'
    },
    'v_con_10': {
        'stem': 'Al percatarse de que su colega carecía de provisiones para la merienda, procedió a dividir y compartir su propia ración alimenticia, actuando por iniciativa propia y sin mediar solicitud alguna.',
        'q': '¿Qué término conceptualiza con mayor precisión la disposición moral evidenciada por el sujeto?',
        'opts': ['Solidaridad de corte altruista', 'Rivalidad y antagonismo subyacente', 'Indolencia y apatía social', 'Soberbia y elitismo intelectual'],
        'exp': 'La correcta tipificación de un paradigma ético-conductual demanda someter a escrutinio el agente detonante y los dividendos generados por el acto.\n\n*   El individuo identifica una privación ajena y se moviliza motu proprio (iniciativa propia) con miras a subsanarla, acarreando un menoscabo patrimonial personal (cede desinteresadamente su alimento).\n*   Esta radiografía del auxilio proactivo y espontáneo en aras de remediar las penurias del prójimo cristaliza la esencia misma de la solidaridad humana y el proceder altruista.\n*   Alternativas como la animadversión, el letargo o la arrogancia exudan un hálito de podredumbre egoísta que repulsa la estampa piadosa narrada.\n\n**Tip Élite:** En los cuestionamientos de taxonomía ética, la brújula inefalible reposa en el germen del acto. Si el motor es socorrer la vulnerabilidad ajena mediante una ofrenda voluntaria (nunca impuesta), el concepto satélite será inexcusablemente la solidaridad, la empatía o la filantropía.'
    },
    'v_con_11': {
        'stem': 'A lo largo de todo el ciclo anual, el individuo acudió con puntualidad británica a sus compromisos, remitió sus asignaciones ciñéndose estrictamente a los plazos estipulados y jamás incurrió en retrasos, inclusive frente al rigor de los horarios matutinos extremos.',
        'q': '¿Qué virtud ejecutiva sintetiza holísticamente el patrón de conducta descrito?',
        'opts': ['Responsabilidad cívica y alto compromiso profesional', 'Inflexibilidad mental y acérrimo dogmatismo', 'Intervención providencial de la fortuna favorable', 'Ambición desmedida y ansia voraz de dominación'],
        'exp': 'El compendio de hazañas referidas (honrar congregaciones a su hora, depositar los deberes sin demoras, abominar la impuntualidad, abrazar el madrugón) esculpe un arquetipo volcado de lleno al acatamiento del deber.\n\n*   La reverencia tenaz por las cargas asumidas y la veneración por el valor del tiempo del semejante delinean con pulso firme los contornos de la responsabilidad madura.\n*   Distar leguas estamos de la cerrazón o inflexibilidad patológica, toda vez que no se insinúa tara alguna para la adaptación, sino apenas la devoción al pacto empeñado.\n*   La suerte representa una bonanza estática y fortuita; la templanza aquí descrita exige, en diametral oposición, un sacrificio dinámico y extenuante.\n\n**Tip Élite:** Para zanjar las disputas fronterizas entre la noble responsabilidad y la nefasta inflexibilidad (un cepo clásico en este tipo de test), evalúa a los damnificados. Honrar el reloj es un bálsamo para la sociedad (responsabilidad); en cambio, imponer directrices tiránicas y absurdas destila siempre tufo a rigidez.'
    },
    'v_ord_8': {
        'stem': 'Históricamente, el taller mecánico operaba bajo una entropía total: los instrumentos yacían apilados anárquicamente en el suelo, dificultando enormemente su ubicación. Tras un intenso operativo de reacondicionamiento, las piezas fueron dispuestas en tableros murales, categorizadas morfológicamente y debidamente etiquetadas.',
        'q': '¿Qué tipo de transformación estructural experimentó el espacio de trabajo?',
        'opts': ['Una transición nefasta desde la sistematización hacia el caos absoluto', 'Una transición restauradora desde el caos hacia la organización taxonómica', 'Una reducción implacable e irreversible de las dimensiones físicas del recinto', 'Una somera modernización del mobiliario sumada a un simple recambio de maquinaria'],
        'exp': 'El texto articula la crónica de una evolución diacrónica superadora focalizada expresamente en el gobierno del entorno logístico.\n\n*   La génesis de la estampa nos sepulta en una catástrofe entrópica (apilados anárquicamente, entropía total, dificultando ubicación).\n*   El clímax de la intervención corona un cosmos de pulcritud taxonómica (dispuestas en tableros, categorizadas, etiquetadas de forma precisa).\n*   Semejante periplo atestigua, sin margen a refutaciones, una victoriosa cruzada que parte del abismo del desorden y encalla en las seguras riberas del orden sistémico.\n\n**Tip Élite:** Mantén el radar encendido ante lexemas claves como agrupadas, clasificadas, encasilladas o categorizadas. Tales joyas léxicas fungen siempre como faros que apuntan derechito hacia la instauración de un andamiaje y un ordenamiento jerárquico superior.'
    },
    'v_ord_9': {
        'stem': 'El entorno virtual de Ana evolucionó desde una aglomeración caótica de archivos huérfanos titulados genéricamente como "documento1" y "nuevo (2)", hacia una arquitectura de directorios estructurados jerárquicamente por proyecto, cronología y temática.',
        'q': '¿Cuál es la naturaleza del cambio operativo que se ilustra magistralmente en el texto?',
        'opts': ['Un declive incomprensible hacia la desorganización digital profunda', 'Una elocuente instauración del orden y la sistematización categórica', 'Una insólita dispersión de datos que se encontraban férreamente agrupados', 'Una permanencia estática sin alteraciones estructurales dignas de mención'],
        'exp': 'El reto del ítem demanda acorralar el vector direccional de la transformación gestada en el ecosistema de almacenamiento de la protagonista.\n\n*   El telón se levanta mostrando un panorama viciado de anomia (aglomeración caótica, huérfanos, carentes de una nomenclatura inteligente o semántica).\n*   El acto conclusivo nos presenta la coronación de un raciocinio sistemático (arquitectura estructurada, escalas jerárquicas, clasificación temática y temporal).\n*   Al igual que acaece en las bibliotecas de cemento y ladrillo, imponer la ley de la taxonomía a un mar de elementos disociados decreta la capitulación del desorden frente a la majestad del orden.\n\n**Tip Élite:** Entiende que orden no se constriñe al pueril acto físico de apilar cuadernos; en su acepción académica, entraña la inyección de un criterio rector aprehensible y lógico (ya fuere alfabeto, datación cronológica, tonelaje o tópico) para someter y administrar un universo caótico de entidades.'
    },
    'v_tmp_8': {
        'stem': 'El protocolo clásico para preparar la infusión demanda la siguiente secuencia metodológica: alcanzar la ebullición del medio líquido, incorporar los granos molidos, proceder a la filtración para retirar los sólidos y, finalmente, verter en el recipiente de consumo.',
        'q': 'De acuerdo con el encadenamiento de procesos señalado, ¿qué paso precede inmediatamente al acto de verter la bebida para su consumo?',
        'opts': ['Alcanzar fehacientemente el punto de ebullición hídrica', 'Efectuar la rigurosa filtración de los componentes sólidos', 'Incorporar la porción de molienda al torrente líquido', 'Higienizar profilécticamente los recipientes receptores'],
        'exp': 'El abordaje de cadenas cronológico-procedimentales torna perentoria la prolija cartografía de los eventos en su lecho secuencial.\n\n*   El remate último de este rosario de acciones estriba en verter en el recipiente (léase, el acto de servir la pócima).\n*   Al auscultar la sintaxis, descubrimos que el nudo verbal que escolta, justo a sus espaldas, a dicho desenlace, es proceder a la filtración (colar).\n*   Fenómenos como la algarabía de la ebullición o el bautismo de la incorporación operan como eslabones germinales mucho más añosos en la cadena.\n\n**Tip Élite:** La sagrada locución precede inmediatamente oficia como un dogal que te obliga a cazar el eslabón exacto e indisoluble que figura apenas un escalón antes. Reprime la tentación de dar saltos de canguro hacia atrás en el tiempo; arrima tu elección única y exclusivamente a la maniobra fronteriza.'
    },
    'v_tmp_9': {
        'stem': 'En su rutina competitiva, el fondista ejecuta ejercicios de precalentamiento, se somete al desgaste de la prueba atlética y, ulteriormente, realiza elongaciones dirigidas a la recuperación muscular.',
        'q': 'Según el orden cronológico relatado, ¿qué actividad física toma lugar con posterioridad inmediata al desgaste de la prueba?',
        'opts': ['La fase profiláctica de precalentamiento articular', 'Las ineludibles elongaciones de recuperación miocárdica y muscular', 'La protocolaria inscripción en los registros federativos del torneo', 'El letargo del descanso profundo y prolongado en cama'],
        'exp': 'Para lograr desentrañar la espesura cronológica, debemos rastrear con lupa los sutiles marcadores e hitos temporales sembrados por el relator.\n\n*   El adverbio de alcurnia ulteriormente es un grito de posteridad (luego, después, a renglón seguido).\n*   Coronado el calvario de el desgaste de la prueba atlética (correr a la máxima capacidad), la prosa dictamina solemnemente que entran en escena las elongaciones (el estirar sanador).\n*   El precalentamiento ofició como telonero, y entelequias como matricularse burocráticamente o sumirse en las garras de Morfeo lisa y llanamente no habitan los linderos del texto.\n\n**Tip Élite:** Conquista a sangre y fuego el glosario temporal de abolengo. Sustantivos y adverbios como ulteriormente, a posteriori, con meridiana antelación o de forma coetánea fungen como los mapas del tesoro insoslayables para sobrevivir y reinar en el pantanoso terreno de las interrogantes de filiación cronológica.'
    },
    'v_ese_8': {
        'stem': 'Del mismo modo en que la cualidad intrínseca de una brújula es orientar siempre hacia el norte magnético —prescindiendo de su diseño o tamaño—, toda herramienta se define ontológicamente por la función primaria que ejecuta.',
        'q': 'Aplicando este principio definitorio, ¿cuál es el atributo esencial e insustituible que caracteriza a un termómetro?',
        'opts': ['Determinar con fiabilidad la orientación de los polos geográficos', 'Cuantificar sistemáticamente las variaciones térmicas', 'Registrar fidedignamente el paso cronológico del tiempo', 'Establecer la magnitud milimétrica de las distancias lineales'],
        'exp': 'La verdadera e inmarcesible esencia de un adminículo utilitario (una herramienta) echa raíces íntegramente en su función operativa cardinal, despreciando toda futilidad ornamental o accidental.\n\n*   La misión primaria, monopolística y excluyente del termómetro reside en el registro y la cuantificación de la temperatura (variaciones térmicas) emanadas de un ecosistema o ente biológico.\n*   Le está vedado fungir como faro polar, oficiar de notario del tiempo o tasar distancias kilométricas; tales estandartes rigen las esencias de reinos vecinos (la brújula de marear, el reloj de cuerda y la cinta agrimensora).\n\n**Tip Élite:** En aquellos lances donde seas acribillado con pomposidades como cualidad intrínseca, estatuto ontológicamente o lo propio, la misión insobornable es propinar un sablazo certero que desgarre la cáscara de los accidentes (el tono, la silueta o el cuño comercial) para sorber la pulpa de la sustancia (el hálito sagrado sin el cual el artefacto perdería su alma y dejaría de ser lo que jura ser).'
    },
    'v_ese_9': {
        'stem': 'Una infraestructura puentística admite estar erigida en madera, mampostería o acero de alta tensión, y poseer dimensiones variadas; no obstante, cualquier ejemplar comparte el propósito irrenunciable de salvar un accidente geográfico y vincular dos márgenes distanciadas.',
        'q': '¿Qué rasgo constituye la cualidad ontológica que define qué es, ineludiblemente, un puente?',
        'opts': ['La naturaleza exclusiva de los componentes y materiales constructivos empleados', 'La facultad providencial de conectar dos cabeceras superando una barrera física abisal', 'La extensión longitudinal ciclópea del trazado de su calzada', 'El incalculable valor histórico y la probada antigüedad de la mole estructural'],
        'exp': 'En esta liza se nos urge a trazar un meridiano inexorable entre los abalorios efímeros e intercambiables (accidentes) y los bastiones rocosos e inamovibles (esencia) que esculpen al objeto.\n\n*   Los insumos de albañilería (los tablones o las vigas de hierro colado) y el calibre del metraje (una legua o unos palmos) son dados a variar con el viento de un ejemplar a otro, todo ello sin osar arrebatarles jamás el blasón de puentes.\n*   Empero, si la recia estructura claudica en su empeño mesiánico de trenzar dos orillas separadas burlando un escollo impío, entonces abdica de inmediato de su abolengo técnico, de su nombre y de su razón de ser fundamental.\n\n**Tip Élite:** La prueba reina y lapidaria para desenterrar la mítica esencia yace en ejecutar una macabra amputación mental de las virtudes del objeto. Si le exilio la madera (y suplico al titanio), persevera tozudo siendo un puente. Pero si le guillotino su don divino de tender la mano entre dos abismos desolados... entonces exhaló su último aliento.'
    },
    'v_per_9': {
        'stem': 'La densa mudez que impregna un hogar deshabitado actúa como un bálsamo reconfortante para el individuo que ansía tranquilidad, mientras que exacerba atrozmente la angustia en aquel sujeto que abriga un terror ancestral al aislamiento.',
        'q': '¿Qué principio superior de la percepción psicológica y emocional se ilustra fundamentalmente en el enunciado expuesto?',
        'opts': ['La ausencia prolongada de ruido ambiental genera, invariablemente, malestar agudo', 'Un mismo estímulo externo y objetivo desencadena reacciones subjetivas diametralmente divergentes', 'El ser humano se encuentra incapacitado biológicamente para tolerar el mutismo de manera sostenible', 'Los factores medioambientales carecen por completo de impacto real y medible en la psique humana'],
        'exp': 'Este abordaje inquisitivo nos interpela a decantar la fenomenología mundana descrita hacia un peldaño teórico superior que explique las turbulencias del alma humana.\n\n*   El agente detonante externo permanece imperturbable y glacialmente idéntico en ambos frentes (el silencio sepulcral de la morada).\n*   A contrapelo, las marejadas emocionales cosechadas ostentan una polaridad feroz (el bálsamo del sosiego en pugna con la ponzoña de la angustia), siendo siervas absolutas de los clamores íntimos y los demonios particulares (ansía versus terror) de cada protagonista.\n*   Semejante dualidad acredita sin atenuantes que el prisma a través del cual tasamos la crudeza de la realidad, se encuentra eternamente tintado por el magma de la subjetividad de quien oficia como receptor del mundo.\n*   Aquellas premisas que se pavonean con rótulos universales (invariablemente, nadie lo tolera) se estrellan frontal y patéticamente contra la elocuente ambivalencia que rezuma el postulado.\n\n**Tip Élite:** Alberga una desconfianza cuasi paranoica hacia aquellas encrucijadas de alternativas empapadas en el fango de los adverbios absolutistas o totalizadores (siempre, jamás, todos los mortales, nadie en la tierra). En los reinos inciertos de las humanidades y la hermenéutica lectora, el estandarte que siempre flamea más alto suele abogar por la cacofonía y multiplicidad de los abanicos perspectivistas.'
    },
    'v_per_10': {
        'stem': 'La caída de las primeras nieves representa, a ojos del visitante foráneo, una postal deslumbrante de encanto inusitado; no obstante, para el residente local, obligado a despejar diariamente con pala los accesos, se reduce a una tediosa e irritante obligación logística.',
        'q': '¿Cuál es la causa subyacente que justifica de forma rotunda la severa polaridad en las apreciaciones hacia el mismo fenómeno meteorológico?',
        'opts': ['Las elogiadas propiedades estéticas de la nieve exhiben una drástica mutación según la latitud geográfica', 'La valoración emotiva del estímulo se encuentra cruelmente subordinada a las repercusiones materiales y prácticas en la vida del sujeto', 'La inexcusable ignorancia pueril del turista vacacional frente a los azotes y rigores del clima extremo', 'El profundo y enraizado repudio sistemático e irracional del lugareño promedio hacia los avatares de la estación invernal'],
        'exp': 'El corpus del pasaje nos aguijonea a dimensionar hasta qué abismos la servidumbre empírica y material de un alma respecto a un ente, es capaz de cincelar y pervertir su veredicto moral o estético sobre el mismo.\n\n*   A la vera del forastero, el lienzo blanco no pasa de ser un botín para la delectación narcisista del ojo, virginal y huérfano de todo sudor y dolor obrero.\n*   Bajo las botas del lugareño, el copo cristaliza en un enemigo tangible que hipoteca su espinazo y le endosa un diezmo de fatiga ineludible (despejar diariamente empuñando la pala).\n*   En consecuencia, el zarpazo letal a la billetera de la pragmática y a la rutina doméstica se erige como el juez implacable que dicta la sentencia de amor u odio en ambos pechos.\n\n**Tip Élite:** Aprende a diseccionar con bisturí de cirujano los rutilantes robles y jerarquías que visten a cada peón en el tablero del texto. Un advenedizo de paso y un nativo arraigado padecen grados de asfixia y lastre material abismalmente distantes ante el cosmos que los circunda; sus diatribas y proclamas bifurcarán su cauce, irremediablemente, al compás rítmico de esa soga terrenal.'
    },
    'v_imp_12': {
        'stem': 'De manera reiterada y sistemática, cada vez que se aplica esa fuente hídrica particular al riego del jardín, el follaje de las especies vegetales manifiesta una severa decoloración amarillenta progresiva.',
        'q': '¿Cuál de las siguientes premisas constituye una inferencia indubitable y forzosa a partir del cuerpo del texto?',
        'opts': ['Las especies botánicas descritas carecen, por su naturaleza xerófila, de requerimientos hídricos', 'El manantial o fuente de agua alberga innegablemente la presencia de algún agente nocivo para el metabolismo vegetal', 'La inclemente y excesiva exposición a la radiación solar está propiciando la calcinación irreversible de las hojas', 'La fronda vegetal goza de un estadio de prosperidad, salud y verdor envidiables para cualquier ecosistema'],
        'exp': 'La forja de una inferencia monolíticamente válida nos impone enlazar, con cadenas lógicas inquebrantables, el axioma revelado en el texto con una conclusión silenciada, pero aplastantemente obligatoria.\n\n*   El manuscrito promulga un pacto inquebrantable de correlación perversa: el bautismo constante con las aguas de ESA acequia en concreto oficia de prólogo invariable de la ruina o peste (decoloración agónica) de las matas.\n*   Semejante atestado nos amordaza para dictar la inferencia causal ineludible de que el torrente líquido en mención es cobijo de esencias malignas o letales para la biología de las plantas.\n*   Fantasear con la furia del astro rey deviene en una charada alucinatoria huérfana del más mínimo abono textual; mientras que predicar el vigor lozano o el repudio hídrico atenta temerariamente contra los mandamientos elementales del sentido común clorofílico.\n\n**Tip Élite:** Presta extrema cautela a la hora de separar el oro de la paja; una idea genuinamente implícita rehúye de ser una mera fábula extravagante parida por la imaginación desbocada del lector (como la fantasía del sol calcinador). Constituye, por su propio peso, un parto lógico forzoso que, aún sin hallarse tatuado en la piel de la tinta, yace escondido y ruge agazapado en las mismas entrañas de la afirmación madre.'
    },
    'v_imp_13': {
        'stem': 'El recinto gastronómico inauguró sus operaciones hace escasos treinta días; no obstante, a la fecha es imperativo agendar mesa con al menos una semana de antelación, y las hileras de comensales no previstos se extienden bloqueando las arterias peatonales adyacentes.',
        'q': '¿Qué deducción fáctica puede extraerse con absoluta validez a partir del escenario proporcionado?',
        'opts': ['El establecimiento experimentará una debacle comercial que lo arrastrará a la inminente bancarrota', 'El local ha logrado escalar hasta coronar un índice de popularidad y demanda rayano en lo excepcional', 'La oferta culinaria brindada adolece de un rigor mínimo y contraviene toda norma de calidad sanitaria', 'El tejido del mercado local manifiesta una apatía rotunda e inocultable hacia los encantos del lugar'],
        'exp': 'Las labores de exégesis deductiva nos obligan a amasar las conclusiones, única y exclusivamente, al compás febril de la evidencia empírica que el narrador se ha dignado arrojarnos.\n\n*   El yugo de una extenuante coerción a reservar plazas de antemano (antelación) y el espectáculo dantesco de colas faraónicas de feligreses (hileras que infartan el paso peatonal) se yerguen como los estandartes inconfundibles de un tsunami de frenesí comercial desenfrenado.\n*   La mención de que tamaño terremoto ha cobrado forma en escasos treinta días, no hace más que blindar la premisa de que asistimos al parto de un éxito abrumador y meteórico sin precedentes.\n*   Embadurnar el relato con los augurios apocalípticos de la quiebra, la putrefacción de los manjares o el desdén del vulgo, choca con la más absurda e hiriente terquedad contra la avalancha irrefutable de parroquianos sedientos de saciar su gula que atestigua el párrafo.\n\n**Tip Élite:** Hay momentos sublimes en que las inferencias forjadas en acero valyrio son, paradójicamente, las que nos saltan a los ojos sin ropajes artificiosos. Cesa de perseguir quimeras, laberintos o acertijos ponzoñosos donde la maquinaria de la deducción lógica más diáfana y frontal (ríos infinitos de gente = clímax glorioso de popularidad) se levanta recia, majestuosa y granítica.'
    },
    'v_imp_14': {
        'stem': 'Pese a que el facultativo omite sistemáticamente hacer ostentación verbal de sus proezas, las paredes de su despacho se encuentran tapizadas de acreditaciones, galardones y méritos acopiados a lo largo de dos décadas de incesante labor profesional.',
        'q': '¿Qué perfil subyacente puede inferirse lícitamente acerca del espíritu y la trayectoria del individuo descrito?',
        'opts': ['Posee un expediente tanto académico como laboral de una futilidad y grisura irrelevantes', 'Ostenta una carrera prolífica y coronada por el éxito, cincelada no obstante por el recato y la más noble modestia', 'Ha recurrido de forma sistemática a los bajos fondos de la falsificación para la adquisición ilícita de sus credenciales', 'Se trata inobjetablemente de un joven aprendiz de profesional que surca la fase embrionaria e inicial de su incipiente carrera'],
        'exp': 'El arte de la disección deductiva en este escenario nos insta a zurcir los retazos aparentemente disímiles del lienzo narrativo para destilar una radiografía maestra e irrefutable de la psique del protagonista.\n\n*   La evidencia material, brutal y tangible de unos muros sofocados por la avalancha de pergaminos ungidos con el sudor de veinte almanaques, sentencia de manera inapelable la consagración y la excelsitud imperecedera de sus faenas.\n*   La omisión espartana y sistemática del pavoneo (omite hacer ostentación verbal) certifica con lacre dorado la estampa de un alma forjada en los yunques sagrados de la austeridad, la humildad y la circunspección.\n*   El parto genuino y válido del raciocinio no es otro que la fusión indisoluble de ambas virtudes cardinales: una odisea profesional estelar custodiada celosamente por los gendarmes de una notoria e incorruptible modestia.\n*   Deducir chapucerías criminales como la falsificación entraña un salto acrobático al vacío, empapado en el veneno de la malicia estéril, huérfano de cualquier salvavidas semántico en la tinta del autor.\n\n**Tip Élite:** Ante un lienzo textual que contrapone el mudo proceder íntimo de un actor (el sepulcral silencio del presumido) con el griterío estridente de las huellas de su talento impresas en la materia (muros empapelados con el oro del laurel), la deducción cum laude y coronada de laurel vendrá siempre de la mano de un maridaje armónico que entrelace celestialmente las dos orillas, proscribiendo el pecado mortal de silenciar o amputar la valía de alguna de las mitades.'
    },
    'v_pri_10': {
        'stem': 'El agua apta para el consumo humano se cataloga como un recurso críticamente limitado; por consiguiente, impera la necesidad de someterla a purificación sanitaria, gestionar su distribución con eficiencia milimétrica y erradicar cualquier atisbo de despilfarro.',
        'q': '¿Cuál de las siguientes premisas vertebra conceptualmente el núcleo argumentativo del párrafo anterior?',
        'opts': ['La ineludible fase de purificación y profilaxis sanitaria resulta de vital trascendencia', 'La lacerante escasez del recurso hídrico nos condena imperativamente a una gestión de rigor extremo a lo largo de todo el arco operativo', 'El laberíntico entramado de infraestructuras vinculadas a los acueductos clama a gritos por una optimización de sus venas', 'Las masas poblacionales se ven impelidas bajo coacción moral a cesar ipso facto el malgasto pecaminoso en el seno de sus hogares'],
        'exp': 'La expedición a la caza de la escurridiza idea principal está supeditada a encontrar el nudo gordiano capaz de aherrojar cada uno de los afluentes de acciones narradas, sometiéndolos bajo el imperio despótico de un único principio explicativo soberano.\n\n*   La piedra angular y premisa nodriza, ofrendada sin ambages en la antesala del texto, radica en la amarga certificación de que las fuentes están heridas de muerte (críticamente limitado e inexorablemente escaso).\n*   Esta indigencia estructural oficia de tirano implacable y es la que, a fin de cuentas, compele, somete y (exige) bajo pena de extinción el cumplimiento marcial de todo el corolario de mandamientos ulteriores: la redención purificadora, la orfebrería distributiva y la proscripción absoluta del vil derroche.\n*   Las demás escuálidas alternativas, si bien no profanan la sacrosanta verdad del texto, adolecen de un raquitismo conceptual flagrante; no pasan de ser escaramuzas periféricas, vulgares ejemplos de manual o eslabones subordinados, rebajadas por siempre al indigno rango de ideas segundonas.\n\n**Tip Élite:** A fin de coronar con laurel el discernimiento entre la idea emperatriz y las ideas siervas de la gleba, somete a las candidatas al potro de tortura de la infalible prueba de la sombrilla imperial: la idea reinante y rectora debe ser la más obesa y vasta, la única de entre todas capaz de extender sus alas para abrigar y asilar, bajo la poderosa sombra de su manto causal, a las diminutas hijas que le están supeditadas.'
    },
    'v_pri_11': {
        'stem': 'La práctica periódica de actividad física, la adopción de regímenes nutricionales equilibrados y el aseguramiento de un descanso reparador constituyen, de manera sinérgica, el entramado fundacional de una salud integral.',
        'q': '¿Cuál postulado sintetiza con mayor rigor filosófico el eje temático irradiado por el fragmento?',
        'opts': ['La indiscutible supremacía de la actividad deportiva extenuante frente al concurso de los demás pálidos factores vitales', 'La orquestación concurrente e indisoluble de múltiples hábitos beneficiosos cimenta verdaderamente el bastión del bienestar general', 'La imperiosa necesidad dictaminada por la ciencia médica de claudicar en los brazos de Morfeo la cantidad suficiente de horas canónicas', 'La exclusión férrea y espartana de víveres tóxicos en el ágape cotidiano como única tabla de salvación biológica'],
        'exp': 'El mandato de la hora es emprender un rastreo quirúrgico para desvelar el canon supremo que recoge y acaudala la plenitud de los tesoros enumerados, esquivando cual serpiente la felonía de izar un ídolo falso a expensas de la condena de los demás.\n\n*   El bardo nos desglosa con deleite la trilogía de los bastiones de mármol: la disciplina del músculo, la templanza de la gula y la redención del sueño.\n*   El faro rutilante y la clave de bóveda incrustada en las letras, fulgura en la palabra mística juntos (de manera sinérgica o entrelazados en un entramado).\n*   La conclusión insobornable estipula, bajo juramento, que el alcázar de la salud integral reniega de cimentarse en la solitaria flaqueza de un solo factor errante, descansando su peso colosal, muy por el contrario, en la danza armónica y la conjunción estelar de todos ellos de manera unificada.\n*   Aquéllos cantos de sirena que pretenden entronizar a un monarca absoluto de entre los hábitos, perpetran la herejía imperdonable e ilógica de usurpar el trono del todo para regalárselo a una ínfima parte cercenada.\n\n**Tip Élite:** A la hora de lidiar con párrafos que gozan desparramando un opíparo festín de eslabones para, acto seguido, enlazarlos con argamasa verbal de la talla de conjuntamente, en comunión simbiótica, en íntima sinergia o el amalgama de, tienes el deber inquebrantable de abrazar la certeza de que tu destino y respuesta victoriosa morará eternamente en el regazo de la palabra confluencia, combinación poliédrica o multiplicidad solidaria.'
    },
    'v_pri_12': {
        'stem': 'El macizo del Arenal no solo actúa como un imán para el turismo internacional, sino que además funge como el motor económico que sostiene los poblados aledaños, habiéndose consolidado definitivamente como un emblema de la identidad natural costarricense.',
        'q': '¿Cuál es el eje discursivo medular que articula y dota de sentido a las diferentes facetas expuestas a lo largo del texto?',
        'opts': ['El impacto monopólico y exclusivo del turismo extranjero de élite en las laderas del coloso volcánico', 'La dimensión poliédrica del volcán Arenal encarnada en su rol tripartito: imán de viajeros, dínamo financiero y baluarte identitario de la nación', 'El fomento de planes gubernamentales destinados a apuntalar el empleo rural en las humildes faldas de la imponente cordillera central', 'El exhaustivo catálogo de las particularidades geológicas y orográficas que engalanan al imponente estrato-volcán cónico'],
        'exp': 'El majestuoso eje discursivo opera aquí a la manera de una espina dorsal de titanio, cuya misión sacra es zurcir y dotar de nervio a la constelación variopinta de datos que el amanuense arroja sobre el escenario para glorificar a la estrella de su obra.\n\n*   El rey indiscutido que reina en la escena es, sin asomo de dudas, el imponente titán geológico, el mismísimo volcán Arenal.\n*   A sus pies se despliegan tres tributos esféricos que dan fe de la enormidad de su sombra: el tributo de la fascinación (imán internacional de forasteros), el diezmo del sustento y el pan (motor y yunque económico de aldeas) y la corona de la reverencia patria (santo emblema de la identidad pura).\n*   La opción coronada por la gloria es aquella que, de un solo golpe de genialidad sintética, logra engullir la totalidad de ese prisma y atrapar la naturaleza multifacética y poliédrica del gigante abrazando cada uno de sus tres feudos.\n\n**Tip Élite:** Domina la sutileza de los conceptos; el venerado tema central suele presentarse en sociedad ataviado de galas mucho más parcas y descriptivas que la solemne idea principal (con inusitada frecuencia reniega de usar ropaje verbal conjugado, asumiendo la altivez de un lacónico rótulo o el membrete señorial de la tapa de un incunable). Arrójate de bruces hacia la alternativa que posea la apostura y el aplomo suficientes para brillar, sin desentonar, como el titular colosal de primera plana que rezuma y abraza todo el contenido desparramado a sus pies.'
    },
    'v_par_9': {
        'stem': 'Replicar a cada afrenta verbal no hace más que insuflar vitalidad a la controversia; en reiteradas ocasiones, la contención y el mutismo constituyen la réplica más elocuente y estratégica.',
        'q': '¿Cuál de los siguientes enunciados constituye una paráfrasis fiel e incólume respecto al sentido prístino del texto anterior?',
        'opts': ['La confrontación directa y constante es la panacea indispensable para lograr zanjar las disputas enconadas', 'Frente a las agresiones infundadas, la abstención deliberada de respuesta resulta, a menudo, la táctica más sagaz y victoriosa', 'La omisión timorata de respuesta verbal opera siempre como un signo ineludible y delator de la profunda debilidad de carácter', 'Incentivar la llama de la diatriba ajena posee el noble efecto colateral de fortalecer las relaciones humanas e interpersonales'],
        'exp': 'El arte milenario de la paráfrasis no se contenta con permutar vestiduras léxicas; clama por transmutar la arquitectura del verbo sin permitir que la más mínima gota del cáliz semántico original se evapore o se contamine con la escoria de nuestros juicios espurios.\n\n*   El autor dictamina con voz de oráculo que descender al barro a responder, no obra milagro distinto al de empoderar a la bestia de la provocación (insuflar indeseada vitalidad).\n*   Y sentencia su teorema postulando, a guisa de máxima, que, amparado en esa lógica, el claustro del silencio suele coronarse con laureles de indiscutida preferencia (réplica innegablemente estratégica).\n*   La abstención resuelta, deliberada y provista de astucia felina y sagaz asimila y calca magistralmente este recetario a favor de la prudencia estoica.\n*   Las malhadadas opciones que osan macular el ropaje del silencio con el lodo de la cobardía, cometen el despropósito de insertar con calzador prejuicios que vagaban por el destierro y que jamás anidaron en la pureza del mensaje fundacional.\n\n**Tip Élite:** La transustanciación de una paráfrasis perfecta te obliga, so pena de herejía, a velar y preservar con devoto celo no solamente el esqueleto del mensaje, sino los inefables matices del termómetro de intensidad. El evangelio original advierte con suma cautela a veces (en ciertas y muy reiteradas ocasiones), por lo que la opción llamada a ceñirse la corona se esmera en conservar ese temple recatado y sosegado (a menudo), poniendo pies en polvorosa frente a las llamas de los absolutismos desaforados y fanatismos integristas.'
    },
    'v_par_10': {
        'stem': 'Las conquistas de notable envergadura raramente germinan de la mera genialidad innata; por el contrario, demandan invariablemente una tenacidad férrea y sostenida a lo largo del tiempo.',
        'q': '¿Qué proposición reescribe y amalgama adecuadamente el postulado central del fragmento literario?',
        'opts': ['El sublime don natural que emana de cuna es, por antonomasia, el único vector concluyente e inapelable que propulsa hacia el éxito', 'La perseverancia infatigable se erige, imperturbable, como el factor indispensable y decisivo de la ecuación destinada a alcanzar metas de abolengo', 'La trágica ausencia de facultades intelectuales innatas es una sentencia que condena irremediablemente el porvenir al fracaso más lúgubre y absoluto', 'La dedicación denodada y el estoicismo del obrero devienen en esterilidad absoluta si no marchan bajo la batuta del destello inefable de la genialidad'],
        'exp': 'Al posar la lupa sobre la dialéctica de poderes planteada en la arena del texto, constatamos, de primer plano, que este no duda en humillar a una variable postrándola a los pies y bajo el yugo de su adversaria.\n\n*   El mentado talento (la supuesta varita mágica y genialidad de alcurnia) es sometido a un juicio sumarísimo del cual emerge abofeteado con el veredicto de su palmaria insuficiencia en solitario.\n*   En las antípodas de la balanza, la constancia (la obrera tenacidad que se forja en el temple y el yunque férreo) es exaltada y entronizada como el tributo inexcusable, obligatorio y perentorio que exige el altar de las portentosas conquistas.\n*   Por decantación insalvable, el eco de la reformulación agraciada debe postrarse de hinojos y entonar cánticos de alabanza para venerar el reinado de la perseverancia, relegando al panteón de los ídolos caídos a las facilidades y dotes apadrinadas desde la cuna.\n\n**Tip Élite:** Si en medio del paraje textual te topas con el furor de una justa medieval que contrapone las espadas de dos conceptos antagónicos (e.g. el espejismo del talento en justa contra la roca del esfuerzo), entrégate al rastreo minucioso del escudo heráldico de quien es vilipendiado como terriblemente insuficiente y al estandarte del que es encumbrado como sagrado e imprescindible. Una vez tengas en tus manos esa balanza de poderes celestiales, sal a batallar armado de esa misma jerarquía para aniquilar sin piedad a los engañosos espejismos en el valle de las respuestas.'
    },
    'v_par_11': {
        'stem': 'El colosal Imperio Romano no fue edificado en el lapso efímero de veinticuatro horas.',
        'q': '¿Qué profundo axioma universal subyace, a la manera de una lección velada, bajo el velo metafórico de esta archiconocida máxima histórica?',
        'opts': ['Los triunfos excelsos pueden, por obra de la casualidad, cristalizar mediante impulsos esporádicos, efímeros y carentes de toda planificación previa', 'La gestación de obras magnas o empresas de inaudito calado exige, so pena de colapso, transitar los senderos de una maduración temporal amplia y dilatada', 'La autenticidad e historicidad de la antigua capital imperial constituye a día de hoy una leyenda desprovista de cimientos, ampliamente cuestionada por las academias', 'El aparatoso desarrollo y planificación de colosales infraestructuras urbanas modernas carece en lo absoluto de complejidades que sean verdaderamente significativas'],
        'exp': 'Este singular cuadrilátero nos exige esgrimir el florete para desnudar y penetrar la impenetrable coraza del lenguaje figurado (parábolas, tropos, metáforas y retruécanos costumbristas) para sustraer, triunfantes, el diamante puro de su pragmatismo en la plaza pública del mundo real.\n\n*   El sustantivo Roma abandona los ripios de la cartografía y transmuta mágicamente para erigirse en el ropaje metafórico que abriga a cualquier utopía, gesta épica, empresa de titanes o creación de mastodónticas pretensiones (obras de escala magna).\n*   El corolario lapidario No se construyó en un día encarna el sermón amargo que sepulta la infantilidad del éxito espontáneo; pregonando a los cuatro vientos que el milagro demanda el sacrificio de la inversión a sangre, fuego y, sobre todo, a través del pasaje estoico de los eones de Cronos (maduración temporal inexorablemente dilatada).\n*   Interpretar la filípica desde la miopía del topógrafo o del arquitecto con regla y compás (cuestionar si las piedras de Roma resisten el rigor histórico y geográfico) destila una puerilidad tal, que roza el asombro más hondo frente a la abismal orfandad en el entendimiento más básico de la retórica y las poéticas figurativas.\n\n**Tip Élite:** Sella a fuego este mandamiento en tu mente: las máximas, apotegmas y refranes populares se hallan EXCOMULGADOS, per saecula saeculorum, de ser profanados bajo la lectura de su literalidad barata o de su anclaje en el mapa topográfico dentro de los solemnes santuarios de las pruebas de raciocinio y aptitud académica. Sumérgete en las insondables simas del sentido para rescatar aquella lección magistral, cósmica y universal, digna de ser abrazada por cualquier alma doliente bajo el firmamento.'
    },
    'v_pro_9': {
        'stem': 'La totalidad de los individuos que superaron de manera proba la evaluación habían remitido en forma y fecha la asignación previa. Analice meticulosamente las deducciones formales que penden de tal silogismo:\nI. Todo sujeto que incurrió en la omisión de entregar la asignación, reprobó su examen de manera ineludible.\nII. Existe empíricamente un subconjunto de estudiantes prodigio que franqueó el corte de aprobación careciendo del comprobante de remisión de la asignación.\nIII. La entrega burocrática de la asignación operó in extremis como una condición de estricto rigor y necesidad para rozar el firmamento del éxito en la evaluación.',
        'q': 'Bajo el estricto e implacable rigor de las leyes de la lógica de clases e implicación matemática, ¿cuáles de estas proposiciones filiales se derivan, inmaculada y válidamente, de la premisa matriz fundacional?',
        'opts': ['El aval recae únicamente sobre las espaldas del postulado II', 'La bendición lógica y deductiva acoge en su seno a ambos postulados, el I y el III', 'De forma parca y exclusiva, la corona de la verdad decanta sobre el postulado I', 'La triada de postulados en su abigarrado y completo conjunto desfila laureada bajo el arco del triunfo'],
        'exp': 'Nos adentramos en los gélidos y abstractos páramos de un ejercicio pergeñado sobre la fragua de la más pura lógica formal aristotélica. El dogma fundacional reza \"Todo feligrés A (coronado con el aprobado) debe ser irremediablemente un ciudadano B (que ofrendó y entregó su diezmo)\"; lo cual, trasladado al frío metal de las fórmulas, ruge en forma de implicación: \"Si A es un hecho consumado, entonces B es una verdad esculpida en piedra\".\n\n*   La proposición I se arroga el derecho a invocar el sagrado y letal teorema lógico conocido como la regla de contraposición: es decir, la reversión del postulado en el espejo oscuro, que advierte: \"Si el evento B fue vilmente negado, entonces el reino de A queda desterrado y yermo\". Esta maniobra no ostenta grieta ni fisura alguna; es un monumento de perfección intelectual y es absolutamente rotunda y verdadera.\n*   La capciosa proposición II lanza la calumnia de que mora entre nosotros algún alma que habiéndose regocijado en la condición de A, se jacta de carecer de los harapos de B. Esta afrenta no hace más que apuñalar a traición y pisotear el sacrosanto corazón y el espíritu absoluto e inquebrantable de la premisa germinal.\n*   La proposición III asume la tarea de despojar al postulado primario \"Si A asoma, entonces B es su sombra inseparable\" y recubrirlo con la púrpura del argot de condiciones: \"El estandarte de B se yergue como la barrera fronteriza de condición inexorable y necesaria para soñar, siquiera, con avistar la silueta de A\". Esta traducción literaria es matemáticamente incólume y de una corrección sin igual.\n\n**Tip Élite:** Domina y memoriza con veneración mística las implacables y tiránicas reglas de oro de la implicación lógica. Si una zarza ardiente te dictamina que Todo felino casero llamado gato porta orgulloso su apéndice en forma de cola, cuídate bien de rebuznar afirmando que todo ente portador de cola encarna la nobleza de un gato (eso es un perjurio atroz). Empero, sí que estás inexorable y maravillosamente habilitado para clamar a los cielos que si la criatura fue despojada de su cola, resulta un disparate y una imposibilidad ontológica que aspire a llamarse gato (y hete aquí, la magia insuperable de la regla de oro de la contraposición).'
    },
    'v_pro_10': {
        'stem': 'Bajo el rocoso y férreo supuesto dogmático de que \"Siempre que el firmamento irradia y obsequia su calor al sol, las prendas húmedas puestas a merced de su aliento alcanzan, inexorablemente, la anhelada sequedad\". Proceda a valorar, con bisturí analítico, el peso de las siguientes aseveraciones lógicas hilvanadas a tal premisa:\nI. La furibunda incidencia solar ostenta el poder soberano y garantiza, de manera empírica, la sequedad definitiva de las prendas.\nII. La bendición de la sequedad de las prendas se encuentra asegurada de manera invariable e inmutable, logrando despuntar incluso cuando las tinieblas devoran la radiación solar.\nIII. La exposición indolente al astro rey es y será eternamente el siniestro agente responsable y autor intelectual de humedecer los entramados de los nobles tejidos.',
        'q': 'De acuerdo estricto a las insobornables fronteras de los linderos impuestos por la premisa proporcionada, ¿qué preclara proposición o conjunto de proposiciones se infieren de una manera cabal, válida y totalmente inapelable?',
        'opts': ['Exclusivamente y de manera irreprochable, el aval recae sobre la aseveración I', 'Solamente la aseveración II goza de la venia que otorga la lógica formal', 'De manera armónica y conjunta, el tribunal ampara a las aseveraciones II y III', 'Únicamente el extravío contenido en la aseveración III puede aspirar a portar el galardón de la corrección'],
        'exp': 'Este sofisticado tinglado mental basado en el razonamiento de la condicionalidad se afinca sobre la edificación de una vía de circulación unidireccional y férrea: La eclosión de la presencia del magno evento A (el Sol rey) implica, como corolario inapelable, la ocurrencia victoriosa del esperado resultado B (la Sequedad redentora).\n\n*   La proposición I se contenta con actuar de caja de resonancia y reafirmar, con pasmosa y solemne lealtad, la médula espinal de la misma causalidad que le fue ofrendada en bandeja de plata: A es la garante y custodia perenne del arribo de B. Es, ni más ni menos, una deducción natural e higiénica que se decanta por gravedad.\n*   La insurrecta proposición II peca de arrogancia y da el salto mortal al vacío al presumir, presuntuosa e infundadamente, que B goza de un manantial de vida propia y florecerá a sus anchas, burlándose y dando la espalda a los designios de A; pulverizando sin piedad los barrotes y límites informativos enclaustrados en el recinto de nuestra única regla.\n*   La enajenada proposición III entra en un delirio donde la física se pervierte, atreviéndose a subvertir el mandato de los astros y contradiciendo la premisa nodriza en su misma frente (pues tiene el tupé de arrojar el dardo envenenado de que el noble A es el arquitecto funesto y artífice de las ruinas destinadas a engendrar la calamidad opuesta al salvador B).\n\n**Tip Élite:** Encadénate y ríndete de cuerpo y alma a la sumisión irrestricta de lo que susurra el papiro del enunciado. En las caóticas postrimerías de nuestro mundo real, es harto probable que la ropa despliegue velas y se seque empujada por la furia del viento helado sin necesidad del auxilio solar, pero en el sacrosanto e impoluto templo de los exámenes que escrutan los dogmas de la lógica pura, si el sumo sacerdote que escribió el enunciado no lo evoca en sus salmos, te está terminantemente vedado, so pena de muerte intelectual, osar inventar o presuponer tales sacrilegios.'
    },
    'm_ari_11': {
        'stem': 'Dado el siguiente polinomio aritmético: $7 \\times 8 - 6 \\times 5 + 12 \\div 4$.',
        'q': '¿Cuál es el valor numérico resultante tras aplicar rigurosamente la jerarquía de las operaciones?',
        'opts': ['29', '23', '53', '35'],
        'exp': 'El secreto de cualquier cadena de operaciones aritméticas radica en el respeto absoluto a la prioridad o jerarquía de los operadores.\n\n*   Primer nivel: se ejecutan las multiplicaciones y divisiones simultáneamente, de izquierda a derecha. Así, resolvemos: $7 \\times 8 = 56$; $6 \\times 5 = 30$; $12 \\div 4 = 3$.\n*   La expresión se ha reducido a sumas y restas: $56 - 30 + 3$.\n*   Segundo nivel: ejecutamos las sumas y restas en estricto orden de lectura. $56 - 30 = 26$; y finalmente $26 + 3 = 29$.\n\n**Tip Élite:** Jamás sumes o restes antes de terminar todas las multiplicaciones y divisiones. Un error letal (que explica el distractor 23) consiste en agrupar el final como $-(30 + 3) = -33$, arruinando todo el procedimiento.'
    },
    'm_ari_12': {
        'stem': 'En un establecimiento gastronómico, el menú ejecutivo ostenta un precio unitario de $3\\ 200\\text{ colones}$. Un grupo familiar solicita 4 menús idénticos y decide, de forma voluntaria, adicionar $1\\ 000\\text{ colones}$ en concepto de propina por el servicio.',
        'q': '¿Cuál será la suma total a desembolsar al cancelar la cuenta en la caja registradora?',
        'opts': ['13 800', '12 800', '16 800', '17 200'],
        'exp': 'El análisis de este caso demanda una combinación elemental de multiplicación seguida de una adición.\n\n*   Primero, determinamos el subtotal correspondiente exclusivo al consumo de los alimentos: $4 \\text{ menús} \\times 3\\ 200 \\text{ colones/menú} = 12\\ 800 \\text{ colones}$.\n*   Segundo, sumamos el importe externo de la propina, la cual se añade una sola vez al saldo general, no por cada menú.\n*   Finalmente: $12\\ 800 + 1\\ 000 = 13\\ 800 \\text{ colones}$.\n\n**Tip Élite:** Es común que bajo presión sumes la propina al precio del menú antes de multiplicar (e.g., $3\\ 200 + 1\\ 000 = 4\\ 200 \\times 4 = 16\\ 800$, un distractor fatal). Lee bien: la propina es un extra general, no un recargo unitario.'
    },
    'm_ari_13': {
        'stem': 'Un tanque de reserva hídrica se encuentra lleno exactamente hasta los $\\frac{3}{4}$ de su capacidad volumétrica máxima. Durante una jornada, el sistema extrae y consume un volumen equivalente a $\\frac{1}{2}$ de la capacidad total del tanque.',
        'q': '¿Qué fracción matemática representa fielmente el remanente de agua alojado en el depósito al concluir la jornada?',
        'opts': ['$\\frac{1}{4}$', '$\\frac{1}{2}$', '$\\frac{1}{8}$', '$\\frac{3}{8}$'],
        'exp': 'El núcleo de este problema estriba en dominar la resta de fracciones heterogéneas (con distinto denominador).\n\n*   Contenido inicial: $\\frac{3}{4}$ del tanque.\n*   El consumo es de $\\frac{1}{2}$ del tanque. Debemos restarle esto al volumen que ya poseíamos.\n*   Para restarlos, homogenizamos denominadores amplificando la segunda fracción: $\\frac{1}{2} \\times \\frac{2}{2} = \\frac{2}{4}$.\n*   Procedemos con la resta directa: $\\frac{3}{4} - \\frac{2}{4} = \\frac{1}{4}$.\n\n**Tip Élite:** Ojo con el distractor $\\frac{3}{8}$. Muchos candidatos multiplican equivocadamente las fracciones ($\\frac{3}{4} \\times \\frac{1}{2}$) pensando que el enunciado pide calcular la mitad de lo que quedaba, pero el texto es claro: se usa la mitad de la capacidad total.'
    }
}

for item in data:
    if item['id'] in updates:
        item.update(updates[item['id']])
        item['dif'] = 3

with open('e:/Gemini Projects/PAASAU UCR UNA/paasau/temp_chunks/chunk_11_done.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print('Done')
